const $=id=>document.getElementById(id);
const labels={generated:'Наша генерация',reference:'Исходный референс',composite:'Композиция',comparison:'Сравнение',detail:'Исторический артефакт'};
const states={planned:'Планировали',not_run:'Не запускали',executed:'Запущено, оценка не зафиксирована',api_failed:'Ошибка API',quality_rejected:'Качество отклонено',accepted:'Принято пользователем',success:'Удачный результат',failed:'Неудачная попытка',mixed:'Смешанный результат',unknown:'Результат не зафиксирован'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function step(id,number,title,meta){const d=el('details',undefined,'archive-step');d.id=id;const s=el('summary'),heading=el('span',undefined,'archive-heading');heading.append(el('span',title,'archive-title'),el('span',meta,'meta'));s.append(el('span',number,'number'),heading);const body=el('div',undefined,'archive-body');d.append(s,body);return {d,body};}
function section(body,title,text){const s=el('section',undefined,'archive-section');s.append(el('h3',title));if(text)s.append(el('p',text));body.append(s);return s;}
function notes(body,items){const dl=el('dl',undefined,'notes');for(const [title,text] of items){const cell=el('div');cell.append(el('dt',title),el('dd',text||'Не зафиксировано'));dl.append(cell);}body.append(dl);}
function link(text,href){const a=el('a',text);a.href=href;a.target='_blank';a.rel='noopener';return a;}
function figure(title,url,caption){const f=el('figure');f.append(el('h4',title));if(url){const a=link('',url),img=el('img');img.src=url;img.loading='lazy';img.alt=caption||title;a.append(img);f.append(a);}else f.append(el('p','Изображение не сохранилось.'));f.append(el('figcaption',caption||title));if(url)f.append(link('Открыть / скачать',url));return f;}
let manifest,chapter=null;const expanded=new Set();
function render(){const q=$('search').value.trim().toLocaleLowerCase(),rows=manifest.entries.filter(e=>(!chapter||e.chapter===chapter)&&[e.title,e.hypothesis,e.change,e.result,e.feedback,e.testMethod,e.decision].join(' ').toLocaleLowerCase().includes(q));$('timeline').replaceChildren();$('status').textContent=rows.length+' шагов · '+manifest.assets.length+' изображений';
for(const e of rows){const uncertainty=e.chronology==='verified'?'':e.chronology==='inferred'?' · Порядок восстановлен по косвенным данным':' · Точная дата или последовательность неизвестна';
const {d,body}=step('history-'+e.id,String(e.order).padStart(2,'0'),e.title,(e.date||'Дата не записана')+' · '+(states[e.status]||e.status)+uncertainty);d.open=expanded.has(e.id);d.addEventListener('toggle',()=>d.open?expanded.add(e.id):expanded.delete(e.id));
section(body,'Что сравниваем',e.hypothesis);notes(body,[['Что изменили',e.change],['Как проверяли',e.testMethod]]);
const comparisons=section(body,'Изображения и сравнение');const grid=el('div',undefined,'images');for(const a of e.images||[])grid.append(figure(labels[a.role]||a.role,'/api/archive/image/'+a.sha256,[a.caption,a.attribution].filter(Boolean).join(' · ')));comparisons.append(grid);if(!grid.children.length)comparisons.append(el('p','Изображение не сохранилось. Запись попытки оставлена в истории.'));
section(body,'Результат и композиция',e.result);section(body,'Обратная связь',e.feedback||'Не зафиксирована');section(body,'Вывод и следующий шаг',e.decision||'Не зафиксировано');section(body,'Ограничения',e.comparisonCaveat||'Не зафиксированы');section(body,'Данные и источники',e.evidence||'Не зафиксированы');$('timeline').append(d);}}
$('search').oninput=()=>manifest&&render();
async function read(path){const r=await fetch(path),d=await r.json();if(!r.ok)throw Error(d.error||r.status);return d;}
read('/api/archive').then(m=>{manifest=m;document.title=m.title;$('introduction').textContent=m.intro||'';for(const c of [null,...m.chapters||[]]){const b=el('button',c?.title||'Все шаги');b.setAttribute('aria-pressed',String(!c));b.onclick=()=>{chapter=c?.id||null;for(const x of $('chapters').children)x.setAttribute('aria-pressed',String(x===b));$('chapter-notes').replaceChildren();if(c)notes($('chapter-notes'),[['Глава',c.title],['Описание',c.summary],['Варианты подхода',c.alternatives],['Почему выбрали этот подход',c.rationale]]);render();};$('chapters').append(b);}render();}).catch(e=>{$('status').textContent=e.message;});
(async()=>{const root=$('generated-runs'),status=$('generated-status');try{const all=await read('/api/studies'),linked=new Set();let runs=0;for(const run of all.runs.filter(r=>r.mode==='live')){const packet=await read('/api/attempt-packet?run='+encodeURIComponent(run.id));if(packet.frozen.planner_request_id)linked.add(packet.frozen.planner_request_id);const {d,body}=step('run-'+run.id,String(++runs),packet.name,packet.created_at+' · '+packet.completed_cards+'/'+packet.expected_cards+' готовы');
const exp=packet.frozen.experiment||{},brief=packet.planner?.input?.input;section(body,'Что сравниваем',exp.hypothesis||'Гипотеза не зафиксирована');notes(body,[['Пожелания продюсера',brief?.producer_comment],['Условия генерации',[packet.frozen.model,packet.frozen.quality,(packet.frozen.native||[]).join(' × ')].filter(Boolean).join(' · ')]]);
for(const card of packet.cards){const s=section(body,card.object?.name||card.object_id,card.status+(card.error?' · '+card.error:'')),grid=el('div',undefined,'images');
if(card.image_url){grid.append(figure('Исходное изображение','/api/asset?job='+encodeURIComponent(card.job_id)+'&kind=raw','Сохранённый результат провайдера'));if(card.result?.foreground_key)grid.append(figure('Прозрачный предмет','/api/asset?job='+encodeURIComponent(card.job_id)+'&kind=foreground','Слой для модульной сборки'));grid.append(figure('Итоговая карточка',card.image_url,'Сохранённая композиция'));}else grid.append(figure('Результат',null,card.status));s.append(grid);
notes(s,[['Категория',card.object?.category],['Проверки',card.result?JSON.stringify(card.result.source_alpha_qa||card.result.alpha||{},null,2):'Результат проверки не сохранён'],['Решение пользователя',card.choice?JSON.stringify(card.choice,null,2):'Не зафиксировано'],['Стоимость по учёту',card.actual_cost_nanodollars==null?'Не подтверждена':'$'+(card.actual_cost_nanodollars/1e9).toFixed(6)]]);
const prompt=el('details',undefined,'archive-data');prompt.append(el('summary','Промпт и параметры'),el('pre',JSON.stringify({prompt:card.object?.prompt,generation:card.object?.generation,composition:card.result?.composition},null,2)));s.append(prompt,link('Открыть карточку в тесте',card.test_url));}
section(body,'Вывод и следующий шаг',exp.decision||'Итоговая оценка попытки не зафиксирована. Решения по карточкам показаны выше.');section(body,'Ограничения','Сохранённые результаты не означают принятие качества. Отсутствующие оценки и расходы не считаются нулевыми.');
const data=section(body,'Данные и источники');data.append(link('Вся коллекция в тесте','/studio/index.html?run='+encodeURIComponent(run.id)),document.createTextNode(' · '),link('Полный пакет попытки',packet.pix.packet_url));root.append(d);}
for(const attempt of (all.attempts||[]).filter(a=>a.job_id.startsWith('planner_')&&!linked.has(a.job_id))){const {d,body}=step('attempt-'+attempt.job_id,'·','Планирование коллекции',attempt.created_at+' · '+attempt.status);section(body,'Что получилось',attempt.error||'Генерация изображений ещё не началась');const s=section(body,'Данные и источники');s.append(link('Журнал планирования','/api/journal?attempt='+encodeURIComponent(attempt.job_id)));root.append(d);}
status.textContent=runs?'Сохранённых попыток генерации: '+runs:'Попытки сохраняются автоматически после запуска. Планирование и ошибки также остаются в архиве.';}catch(e){status.textContent='Свои попытки доступны в сессии, где запускалась генерация. '+e.message;}})();
