export const COLLECTION_POLICY_VERSION='collection-quality/v2-story';
export const semanticFamilies=['instrument','audio_equipment','clothing_accessory','printed_material','recorded_media','furniture','container','tool','lighting','architecture','decoration','food','game','transport','other'];
export const collectionRules=`NON-NEGOTIABLE USER RULES FOR C1, C2, C3 AND C4:
No living creatures anywhere: no living plants or flowers, no people, musicians, performers, audience, animals, birds, fish, insects, pets, imaginary creatures, body parts, faces, silhouettes, portraits, photos, statues or motifs depicting them. Use inanimate objects and unoccupied environments only. Never invent occupants to make C4 a scene. Do not remove the scene category; make an empty, object-led environment.
C2/C3 CLASSIFICATION: Category depends on the actual receiving surface and layout, not object identity or construction complexity. A turntable chassis, record platter, appliance base or other attached part is part of the subject, NOT a developed receiving surface qualifying it for C3. A vinyl record/turntable on a simple horizontal tabletop with a basic background is C2. An isolated record without ground is C1. C3 requires a separately recognizable developed meaningful receiving surface; do not relabel C2 as C3 just to meet quotas. Design a genuinely different C3 card instead.
C3 AND C4 ARE DISTINCT COMPOSITIONS: C3 is an inanimate subject on its developed meaningful surface against a BASIC colored gradient/pattern background, with no detailed surroundings, room, landscape or architectural location. C4 embeds the focal inanimate subject INTO A DETAILED RECOGNIZABLE ENVIRONMENT OR DETAILED SCENE-FILLING SURFACE with depth and meaningful spatial context, never a subject/small platform against the same basic backdrop. Plan C3 receiving surfaces without enclosing architecture; plan C4 environment layout or a continuous elaborated surface that forms the full scene. A football on a developed football pitch with coherent field markings qualifies as C4 without architecture or occupants. NO STANDARD BACKGROUND IN C4: no basic gradient backdrop, rings, generic decorative pattern, solid-color backing or white margin. The environment or detailed surface itself fills the background. Both remain whole opaque cards. No living beings in either.
NO TEXT IN IMAGES — HARD RULE FOR ALL C1-C4: No readable or unreadable text, letters, numerals, captions, labels, signage lettering, logos, watermarks, typography or pseudo-text anywhere on the canvas, including objects, screens, posters, tickets, books and environment. Never render collection/category/card titles inside the image; titles exist only in the site UI. Use unlettered forms or broad non-text visual symbols only when meaningful; do not replace words with scribbles or tiny glyph-like marks. Preserve object recognizability without writing. Producer themes do not authorize text.
CATEGORY NAMING — HARD RULE: The category name is ONLY the place or event itself: 'Джаз-клуб', 'Выпускной', 'Кинофестиваль', 'Jazz club', 'Graduation'. No narrative/time framing such as 'вечер в', 'поход в', 'день на', 'ночь в', 'мы пошли', 'an evening at', 'a day at', 'a visit to' or 'our trip'. A jazz-club category is simply 'Джаз-клуб'. The highlight explanations belong in theme_role, never in the category title.
EVENT STORY (mandatory): Every thematic category is a visit to a place/event or an experienced occasion: "we went to a jazz club", "we experienced graduation". For a broad theme infer a specific occasion, not a product taxonomy. Tell what we noticed and did through inanimate traces and objects; the implied visitor is never depicted. NON-CHRONOLOGICAL HIGHLIGHTS: Select the most vivid, memorable moments of the day, not the consecutive logistics of attending. No mandatory beginning/development/ending or causal connection to the previous card. Avoid arrival ticket -> cloakroom tag -> seat -> departure, routine service objects and generic event inventory unless explicitly requested or central to a genuinely exceptional moment. Each card must capture a distinctive highlight through an interesting inanimate focal object, its meaningful state or scene. Prefer surprising but recognizable event-specific details, playful discoveries and peak moments; no arbitrary surrealism or unrelated props. theme_role explains why this moment is memorable. Arrange the highlights freely for thematic resonance and visual rhythm, not chronology. Array order is the curated presentation order. NEVER sort/group by C1-C4; keep the exact required type counts while distributing types along the story. Avoid adjacent identical production types whenever the count permits.
ADJACENT VISUAL RHYTHM: Consecutive cards must have distinct composition_key values, focal silhouette/placement, camera framing and semantic families. A microphone and sheet music must not both become the same centered upright object on the same platform; redesign one composition/type without breaking the story or quotas. Do not reorder the finished story randomly for visual variation. Assigned neighboring background/environment hue families are different; also vary dominant subject material hues between neighboring cards without violating explicit user colors or reference material treatment.
SUBJECT/BACKGROUND SEPARATION: The dominant object color must not merge with its backdrop or receiving surface. Choose subject material color compatible with the assigned surroundings, preserve reference saturation/value, and separate with clearly different hue and/or readable lightness. Gold/brass on yellow/gold, cyan on cyan, purple on purple are prohibited when silhouette blends. No white outline, halo, artificial oversaturation or bleaching to repair contrast. C4 also separates the focal subject from detailed surroundings; no standard backdrop.
C4 NO MANDATORY SURFACE: No required ground, table, pedestal, receiving plane or visible base contact. A lighthouse against a broad stylized sky and a small number of simple clouds is valid C4; do not add a platform. Use coherent scenic context, never a generic abstract gradient/pattern background. Limit context to ONE OR TWO large simple supporting forms. Do not populate the scene with decorative architecture, tiny accents or secondary objects. The focal subject remains complete and within approved size limits.
C4 ART-DIRECTION PRIORITY: The focal object remains the hero, with reference-matched clean rounded casual-game volume and material colors. A detailed location means one or two broad readable supporting forms, not photographic detail, panoramic architectural rendering, numerous decorative props or multiple competing highlights. Use a quieter environment with reduced edge density and contrast; the subject has the strongest silhouette and identity detail. Avoid cinematic lighting, photo depth-of-field, bokeh, lens effects and realistic glossy room materials. Plan the complete focal bounding box at 60-72% of the limiting canvas dimension, never above 78% width/76% height, excluding the receiving surface and background. C4 does NOT permit a standard background.
A thematic category is NOT one product family. For ten cards use at least FOUR distinct semantic families, no family more than THREE times. Different musical instruments all count as instrument; changing scene, camera or accessories does not change the main subject family. Jazz may combine instruments, a microphone, a fedora, a vinyl record, sheet music, a club sign, audio equipment, empty club furniture; these are examples, not a fixed inventory. C4 scenes must have distinct inanimate focal identities too.
Choose the primary semantic_family from the schema and living_creatures='none'. Provide factual_checks: two or three concrete, object-specific construction requirements, not generic claims of correctness. For drums, bass-drum beater and pedal attach on the rear batter-head side facing the drummer position; the audience-facing resonant head has no pedal. Hi-hat pedal also faces the drummer position. Position the stool behind the bass drum, even if occluded; do not expose pedals on the front just to show details.
For perspective, specify one camera elevation and shared ground plane; horizontal coplanar lines use compatible vanishing directions, circular drumheads use ellipses consistent with their individual real tilts, stands contact one receiving plane, hardware attaches physically. No twisted stage or incompatible edge directions.
Focal object/group including handles and attachments, excluding receiving surface/background/shadow: at most 78% canvas width and 76% height in C1-C3; target 60-72% width or height on the limiting dimension, never enlarge a narrow object just to fill both. C4 focal cluster also stays within 78% width and 76% height; environment may fill canvas. The approved illustration style, material saturation and reference treatment remain unchanged. FRAME THE COMPLETE SUBJECT, NOT AN INTERNAL COMPONENT: For a turntable the focal bounding box includes the full chassis, all feet, platter/record, controls and tonearm; the record disc alone is not the measured object. For a drum kit include every drum, cymbal, stand and attached part of the focal group. Keep the entire subject inside the canvas with at least 11% canvas width of clear surroundings at EACH side and at least 12% canvas height above and below its complete silhouette. These margins contain the category-permitted backdrop, surface or scene, never white borders. Prefer a 60-72% limiting-dimension subject; the 78% width/76% height values are ceilings, not targets. A wide low subject should occupy about 60-72% WIDTH, not be enlarged until its height fills the card. Pull the camera back if any attached part reaches the frame; never crop, stretch, omit or detach parts to satisfy scale. Reference close-ups teach Art Direction, not permission to copy oversized framing.
`;
export function validateCategoryInventory(objects){
 if(!Array.isArray(objects)||!objects.length)throw Error('Empty thematic category');
 const counts=new Map();
 for(const o of objects){
  if(o.living_creatures!=='none')throw Error('Живые существа запрещены во всех C1–C4. Генерация не отправлена.');
  if(!semanticFamilies.includes(o.semantic_family))throw Error('Нужен тип предмета для проверки разнообразия.');
  if(!Array.isArray(o.factual_checks)||o.factual_checks.length<2||o.factual_checks.some(s=>typeof s!=='string'||s.trim().length<12))throw Error('Нужны конкретные проверки конструкции предмета.');
  counts.set(o.semantic_family,(counts.get(o.semantic_family)||0)+1);
 }
 const max=Math.max(1,Math.ceil(objects.length*.3)),min=Math.min(4,objects.length);
 if(counts.size<min||[...counts.values()].some(n=>n>max))throw Error('Категория однообразна: нужны разные типы предметов, не только разные модели одного типа. Генерация не отправлена.');
}
const palettes=['gold','purple','cyan','pink','green'];
const patterns=['concentric-rings','stripes','polka-dots','checkerboard','honeycomb','triangles','chevrons','waves','scallops','crosses','stars','grid','herringbone','spirals','plain-gradient'];
function randomFor(seed){let n=2166136261;for(const c of seed)n=Math.imul(n^c.charCodeAt(0),16777619)>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
function shuffled(a,random){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function categoryVisualSchedule(count,seed){
 const random=randomFor(String(seed)),limits=Object.fromEntries(palettes.map(p=>[p,2+Math.floor(random()*2)]));
 for(const hue of shuffled(palettes,random)){if(Object.values(limits).reduce((a,b)=>a+b,0)>=count)break;limits[hue]=3;}
 if(count>Object.values(limits).reduce((a,b)=>a+b,0)||count>patterns.length)throw Error('Не хватает цветов без повторов: уменьшите категорию до 10 карточек или разделите её.');
 // Balanced first two passes, then optional third appearances; no independent per-card lottery.
 const remaining={...limits},deck=[];
 for(let i=0;i<count;i++){const choices=shuffled(palettes.filter(h=>remaining[h]>0&&h!==deck.at(-1)),random).sort((a,b)=>remaining[b]-remaining[a]);if(!choices.length)throw Error('Не удалось разделить соседние цвета.');const hue=choices[0];deck.push(hue);remaining[hue]--;}
 const patternDeck=shuffled(patterns,random);
 return Array.from({length:count},(_,i)=>({version:COLLECTION_POLICY_VERSION,background_palette:deck[i],background_pattern:patternDeck[i],palette_repeat_limit:limits[deck[i]],pattern_repeat_limit:1}));
}
export function visualInstructions(v,category){
 if(category==='C4')return 'FROZEN CATEGORY VARIATION: Dominant environment/surface palette family '+v.background_palette+'. Keep subject material colors and clear contrast. C4 MUST use a detailed environment OR detailed scene-filling surface; no standard background, abstract gradient backdrop, rings, generic decorative pattern or solid backing. Do not render the assigned basic-background pattern in C4. Meaningful natural/architectural/field details form the context instead; preserve the approved clean illustrated style.';
 return 'FROZEN CATEGORY VARIATION: For C1-C3 the basic background dominant hue family MUST be '+v.background_palette+'; for C4 this is the dominant environment palette, while its detailed spatial environment remains mandatory. Use ONLY background pattern type '+v.background_pattern+' (plain-gradient means no pattern). Do not add musical-note motifs, rings or a second pattern type. This assignment is scheduled across the category: hue at most '+v.palette_repeat_limit+' appearances, each pattern type at most once. Keep the existing subtle pattern contrast and gradient. In C4 any assigned motif is subordinate and integrated into an appropriate environmental surface, not a flat decorative backing that replaces the location. For C2 choose a similar or contrasting surface hue compatible with this fixed background and subject readability; do not override the assigned background hue.';
}

export function validateNarrativeSequence(objects){
 if(!objects.every(o=>typeof o.theme_role==='string'&&o.theme_role.trim().length>=12&&typeof o.composition_key==='string'&&o.composition_key.trim()))throw Error('Нужны яркие моменты и описания композиций карточек.');
 // Highlights have no chronological dependency. Curate existing objects, never relabel them.
 let beam=[{order:[],used:0,score:0}];
 for(let depth=0;depth<objects.length;depth++){
  const next=[];
  for(const state of beam)for(let i=0;i<objects.length;i++)if(!(state.used&(1<<i))){
   const previous=objects[state.order.at(-1)],o=objects[i];
   const penalty=previous?(previous.composition_key===o.composition_key?100:0)+(previous.production_category===o.production_category?10:0)+(previous.semantic_family===o.semantic_family?3:0):0;
   next.push({order:[...state.order,i],used:state.used|(1<<i),score:state.score+penalty+Math.abs(depth-i)*.001});
  }
  next.sort((a,b)=>a.score-b.score);const seen=new Set();beam=next.filter(x=>{const key=x.used+':'+x.order.at(-1);if(seen.has(key))return false;seen.add(key);return true;}).slice(0,32);
 }
 const arranged=beam[0].order.map(i=>objects[i]);objects.splice(0,objects.length,...arranged);
 const warnings=[];
 for(let i=1;i<objects.length;i++)if(objects[i-1].composition_key===objects[i].composition_key)warnings.push('Проверьте различие композиций соседних карточек '+i+' и '+(i+1)+'.');
 return warnings;
}
