import {defaults,plannerPayload,imagePayload} from './studio/flow-model.mjs';
export const PAGE_SIZE=10;
export function collectionBrief(name,wishes){return {...defaults(),theme:name.trim(),collection_name:name.trim(),producer_comment:wishes.trim(),card_count:PAGE_SIZE};}
export function plannedCollection(draft,plan){const objects=(plan.collections||[]).flatMap(c=>c.objects);if(objects.length!==PAGE_SIZE)throw Error('План должен содержать ровно 10 карточек.');if(objects.some(o=>o.production_category==='C3'&&o.asset_stage!=='object_with_surface'))throw Error('Для C3 нужна единая сборка предмета и поверхности.');const d={...draft,objects:objects.map(o=>({object_id:o.object_id,name:o.main_identity,category:o.production_category,brief:[o.object_brief,...[['Contents',o.contents],['Surface decoration',o.decoration]].filter(([,a])=>a?.length).map(([label,a])=>label+': '+a.map(x=>x.description).join('; '))].join('\n')})),approved:true};imagePayload(d);return d;}
export function categoryFor(job,alpha){if(['C1','C2','C3','C4'].includes(job.category))return {category:job.category,evidence:'Из плана коллекции'};if(!alpha)return {category:null,evidence:'Тип не определён'};const {data,width,height}=alpha;let opaque=0,left=0,right=0;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const a=data[(y*width+x)*4+3];if(a>245)opaque++;if(a>30&&y>height*.65){if(x<width*.02)left++;if(x>width*.98)right++;}}if(opaque/(width*height)>.98)return {category:'C4',evidence:'Предварительно: цельная сцена по геометрии изображения'};if(left>height*.1&&right>height*.1)return {category:null,evidence:'Поверхность требует проверки C2 / C3 во вкладке «Тест»'};return {category:'C1',evidence:'Предварительно: изолированный предмет по альфа-маске'};}
function shuffle(items,random){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
export function sameCategoryReferences(refs,category,random=Math.random){return category?shuffle([...new Map(refs.filter(r=>r.category===category&&!r.categoryEvidence?.alternatives?.length).map(r=>[r.id,r])).values()],random).slice(0,5):[];}
export function blindComparison(refs,category,random=Math.random){const originals=sameCategoryReferences(refs,category,random);return originals.length?shuffle([...originals.map(reference=>({reference})),{generated:true}],random):[];}
export {plannerPayload,imagePayload};
