import {cardActions} from './card-actions.mjs';
import {plannerStopped,plannerProgress,imageProgress} from './generation-progress.mjs';
import {PAGE_SIZE,collectionBrief,plannedCollection,plannerPayload,imagePayload,categoryFor,blindComparison} from './generator-model.mjs';
const $=id=>document.getElementById(id),key='card-studio-generator/v2';let saved=JSON.parse(localStorage.getItem(key)||'{}'),runId=null,jobs=[],refs=[],page=0,busy=false,ready=false,serial=0,selection=0;const rendered=new Map(),persist=()=>localStorage.setItem(key,JSON.stringify(saved));
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error((d.error||String(r.status))+' · '+path.split('?')[0]+(d.diagnostic?' · '+d.diagnostic:''));return d;}
function text(id,value){$(id).textContent=value;}function node(tag,label){const el=document.createElement(tag);if(label)el.textContent=label;return el;}
$('collection-name').value=saved.name||'';$('producer-wishes').value=saved.wishes||'';
for(const id of ['collection-name','producer-wishes'])$(id).oninput=()=>{saved.name=$('collection-name').value;saved.wishes=$('producer-wishes').value;saved.pending=null;persist();};
function placeholder(index,job){const b=node('button');b.type='button';b.className='collection-card placeholder';b.disabled=true;b.append(node('span',String(index+1)),node('span',job?.object_id||'Карточка'));b.firstChild.className='slot-number';b.lastChild.className='card-label';return b;}
async function fullCard(job){if(rendered.has(job.id))return rendered.get(job.id);const image=new Image();image.src='/api/asset?job='+encodeURIComponent(job.id);image.alt=job.name||job.object_id;await image.decode();const card={image,type:categoryFor(job,null)};rendered.set(job.id,card);return card;}
async function showPage(){$('comparison-hint').hidden=false;$('selected-card-info').hidden=true;const ticket=++serial,start=page*PAGE_SIZE,visible=jobs.slice(start,start+PAGE_SIZE);$('card-grid').replaceChildren(...Array.from({length:PAGE_SIZE},(_,i)=>placeholder(start+i,visible[i])));$('previous').disabled=page===0;$('next').disabled=start+PAGE_SIZE>=jobs.length;for(const [i,job] of visible.entries()){if(job.status!=='complete')continue;try{const card=await fullCard(job);if(ticket!==serial)return;const b=node('button');b.type='button';b.className='collection-card';b.setAttribute('aria-label',job.name||job.object_id);b.setAttribute('aria-pressed','false');const art=node('span');art.className='card-art';art.append(card.image);const label=node('span',job.name||job.object_id);label.className='card-label';b.append(art,label);b.onclick=()=>selectCard(job,card,b);const slot=node('div');slot.className='card-slot';const actions=node('div');actions.className='card-actions';const urls=cardActions(runId,job),save=node('a','Сохранить PNG');save.href=urls.download;save.download=urls.filename;save.setAttribute('aria-label','Сохранить '+(job.name||job.object_id)+' в PNG');const test=node('a','В тест');test.href=urls.test;test.setAttribute('aria-label','Открыть '+(job.name||job.object_id)+' в тесте');actions.append(save,test);slot.append(b,actions);$('card-grid').children[i].replaceWith(slot);}catch(e){if(ticket!==serial)return;text('collection-status','Карточка '+job.object_id+': изображение недоступно. '+e.message);}}}
async function selectCard(job,card,button){const ticket=++selection;if(!refs.length){try{refs=(await api('/api/references')).references;}catch{refs=[];}}if(ticket!==selection)return;for(const b of $('card-grid').querySelectorAll('button.collection-card'))b.setAttribute('aria-pressed',String(b===button));$('comparison-hint').hidden=true;$('selected-card-info').hidden=false;text('selected-name','Слепое сравнение');text('selected-type',card.type.category||'Тип уточняется');const items=blindComparison(refs,card.type.category);$('original-cards').replaceChildren(...items.map((item,i)=>{const f=node('figure'),img=node('img');img.src=item.generated?card.image.src:'/api/references/image?id='+encodeURIComponent(item.reference.id);img.alt='Карточка '+(i+1);f.append(img,node('figcaption',String(i+1)));return f;}));text('comparison-status',items.length?'Среди оригиналов этой категории — одна наша карточка. Повторный клик перемешает набор.':'Подходящие оригиналы не найдены. Проверка типа — во вкладке «Тест».');}
async function loadRun(id){runId=id;const d=await api('/api/run?run='+encodeURIComponent(id));jobs=d.jobs;page=Math.min(page,Math.max(0,Math.ceil(jobs.length/PAGE_SIZE)-1));text('collection-title',d.run.name);text('collection-status','Готово '+jobs.filter(j=>j.status==='complete').length+' / '+jobs.length+' · страницы по 10 карточек');await showPage();}
$('previous').onclick=()=>{page--;showPage();};$('next').onclick=()=>{page++;showPage();};
const wait=()=>new Promise(resolve=>setTimeout(resolve,5000));
async function launch(){if(busy)return;busy=true;$('launch').disabled=true;$('collection-name').disabled=true;$('producer-wishes').disabled=true;try{text('launch-status','Проверяем подключение…');await refreshReadiness({resume:!!saved.pending?.planId});const draft=collectionBrief($('collection-name').value,$('producer-wishes').value);plannerPayload(draft);saved.pending||={plannerKey:crypto.randomUUID(),runKey:crypto.randomUUID(),name:draft.collection_name,wishes:draft.producer_comment};const p=saved.pending;p.startedAt||=Date.now();persist();text('launch-status',plannerProgress({stage:'queued'},Date.now()-p.startedAt));if(!p.planId){const r=await api('/api/plan-live',{...plannerPayload(draft),requestId:p.plannerKey,approval:'I approve one paid planner attempt'});p.planId=r.requestId;persist();}let plan;for(let i=0;i<120;i++){const r=await api('/api/planner?id='+encodeURIComponent(p.planId));text('launch-status',plannerProgress(r,Date.now()-p.startedAt));if(r.result?.validation_error)throw Error('План не прошёл проверку: '+r.result.validation_error);if(r.result?.plan){plan=r.result.plan;break;}if(r.error?.startsWith('Invalid redirect value, must be one of')){const recovery=await api('/api/planner-recover',{requestId:p.planId});if(recovery.not_sent){saved.pending=null;persist();throw Error('Запрос не был отправлен в API. Резерв снят; нажмите ЗАПУСТИТЬ для новой попытки.');}}if(plannerStopped.has(r.status)||plannerStopped.has(r.stage))throw Error('План остановлен: '+(r.error||r.stage||r.status)+'. Платная попытка не повторяется.');await wait();}if(!plan)throw Error('План ещё не готов. Повторное нажатие проверит эту же попытку.');const approved=plannedCollection(draft,plan);text('launch-status','2/3 · План готов. Отправляем 10 карточек в очередь…');if(!p.runId){const r=await api('/api/runs',{...imagePayload(approved),requestId:p.runKey,planner_request_id:p.planId,mode:'live',approval:'I approve one paid attempt per object'});p.runId=r.runId;saved.runId=r.runId;persist();}for(let i=0;i<120;i++){await loadRun(p.runId);if(jobs.every(j=>j.status==='complete'||plannerStopped.has(j.status)))break;text('launch-status',imageProgress(jobs));await wait();}if(jobs.every(j=>j.status==='complete')){saved.pending=null;persist();}text('launch-status',jobs.every(j=>j.status==='complete')?'3/3 · 10/10 карточек готовы. Вся попытка автоматически сохранена в архиве.':'Незавершённые попытки доступны во вкладке «Тест».');}catch(e){text('launch-status',e.message);}finally{busy=false;$('launch').disabled=false;$('collection-name').disabled=false;$('producer-wishes').disabled=false;}}
$('launch-form').onsubmit=e=>{e.preventDefault();launch();};
async function refreshReadiness({resume=false}={}){const state=await api('/api/preflight');const reasons=[...(state.missing||[]),...(state.live_missing||[]),...(state.planner?.missing||[]),...(state.budget?.live_blockers||[]).filter(reason=>!resume||reason!=='attempt_billing_reconciliation_required')];if(!state.live_enabled)reasons.push('Генерация отключена');if(!state.planner?.live)reasons.push('Планировщик отключён');if(state.planner?.ready===false&&!state.planner.missing?.length)reasons.push('Планировщик не готов');ready=reasons.length===0;if(!ready)throw Error('Запуск недоступен: '+[...new Set(reasons)].join(', '));return state;}
await showPage();text('launch-status','Проверяем подключение…');try{await refreshReadiness();text('launch-status','API готов. Укажите коллекцию и нажмите ЗАПУСТИТЬ.');}catch(e){text('launch-status',e.message);}
try{refs=(await api('/api/references')).references;}catch{refs=[];}
try{}catch(e){text('collection-status','Не удалось загрузить сохранённые коллекции: '+e.message);}
