import {PAGE_SIZE,collectionBrief,plannedCollection,plannerPayload,imagePayload,categoryFor,blindComparison} from './generator-model.mjs';
import {drawCalibrated,calibratedAlternatives} from './studio/editor-bridge.js';
const $=id=>document.getElementById(id),key='card-studio-generator/v2';let saved=JSON.parse(localStorage.getItem(key)||'{}'),runId=saved.runId||null,jobs=[],refs=[],page=0,busy=false,ready=false,serial=0,selection=0;const rendered=new Map(),persist=()=>localStorage.setItem(key,JSON.stringify(saved));
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const d=await r.json();if(!r.ok)throw Error(d.error||String(r.status));return d;}
function text(id,value){$(id).textContent=value;}function node(tag,label){const el=document.createElement(tag);if(label)el.textContent=label;return el;}
$('collection-name').value=saved.name||'';$('producer-wishes').value=saved.wishes||'';
for(const id of ['collection-name','producer-wishes'])$(id).oninput=()=>{saved.name=$('collection-name').value;saved.wishes=$('producer-wishes').value;saved.pending=null;persist();};
function placeholder(index,job){const b=node('button');b.type='button';b.className='collection-card placeholder';b.disabled=true;b.append(node('span',String(index+1)),node('span',job?.object_id||'Карточка'));b.firstChild.className='slot-number';b.lastChild.className='card-label';return b;}
async function fullCard(job){if(rendered.has(job.id))return rendered.get(job.id);const image=new Image();image.src='/api/asset?job='+encodeURIComponent(job.id);await image.decode();const info=await api('/api/image-info?job='+encodeURIComponent(job.id));let alternatives=job.alternatives?JSON.parse(job.alternatives):null;if(!alternatives){alternatives=await calibratedAlternatives(job,image,info.final_sha256);await api('/api/candidates',{jobId:job.id,alternatives});job.alternatives=JSON.stringify(alternatives);}const prior=job.choice?JSON.parse(job.choice):null,a=alternatives.find(a=>a.id===prior?.selected)||alternatives[0],canvas=node('canvas');canvas.width=860;canvas.height=960;await drawCalibrated(canvas,a,job,image,info.final_sha256);const alphaCanvas=node('canvas');alphaCanvas.width=image.naturalWidth;alphaCanvas.height=image.naturalHeight;alphaCanvas.getContext('2d').drawImage(image,0,0);const alpha=alphaCanvas.getContext('2d').getImageData(0,0,alphaCanvas.width,alphaCanvas.height);const pixels=canvas.getContext('2d').getImageData(0,0,860,960).data;let mismatch=0,nonopaque=0;for(let n=0;n<pixels.length;n+=4){nonopaque+=pixels[n+3]!==255;if(alpha.data[n+3]===255)mismatch+=pixels[n]!==alpha.data[n]||pixels[n+1]!==alpha.data[n+1]||pixels[n+2]!==alpha.data[n+2];}if(nonopaque||mismatch)throw Error('Проверка альфа-канала или сохранности предмета не пройдена');const type=categoryFor(job,alpha),card={canvas,type,alternative:a,qa:{nonopaque,mismatch}};rendered.set(job.id,card);return card;}
async function showPage(){$('comparison-hint').hidden=false;$('selected-card-info').hidden=true;const ticket=++serial,start=page*PAGE_SIZE,visible=jobs.slice(start,start+PAGE_SIZE);$('card-grid').replaceChildren(...Array.from({length:PAGE_SIZE},(_,i)=>placeholder(start+i,visible[i])));$('previous').disabled=page===0;$('next').disabled=start+PAGE_SIZE>=jobs.length;for(const [i,job] of visible.entries()){if(job.status!=='complete')continue;try{const card=await fullCard(job);if(ticket!==serial)return;const b=node('button');b.type='button';b.className='collection-card';b.setAttribute('aria-label',job.name||job.object_id);b.setAttribute('aria-pressed','false');const art=node('span');art.className='card-art';art.append(card.canvas);const label=node('span',job.name||job.object_id);label.className='card-label';b.append(art,label);b.onclick=()=>selectCard(job,card,b);$('card-grid').children[i].replaceWith(b);}catch(e){if(ticket!==serial)return;text('collection-status','Карточка '+job.object_id+': сборка недоступна. '+e.message);}}}
async function selectCard(job,card,button){++selection;for(const b of $('card-grid').querySelectorAll('button'))b.setAttribute('aria-pressed',String(b===button));$('comparison-hint').hidden=true;$('selected-card-info').hidden=false;text('selected-name','Слепое сравнение');text('selected-type',card.type.category||'Тип уточняется');const items=blindComparison(refs,card.type.category);$('original-cards').replaceChildren(...items.map((item,i)=>{const f=node('figure'),img=node('img');img.src=item.generated?card.canvas.toDataURL('image/png'):'/api/references/image?id='+encodeURIComponent(item.reference.id);img.alt='Карточка '+(i+1);f.append(img,node('figcaption',String(i+1)));return f;}));text('comparison-status',items.length?'Среди оригиналов этой категории — одна наша карточка. Повторный клик перемешает набор.':'Подходящие оригиналы не найдены. Проверка типа — во вкладке «Тест».');}
async function loadRun(id){runId=id;const d=await api('/api/run?run='+encodeURIComponent(id));jobs=d.jobs;page=Math.min(page,Math.max(0,Math.ceil(jobs.length/PAGE_SIZE)-1));text('collection-title',d.run.name);text('collection-status','Готово '+jobs.filter(j=>j.status==='complete').length+' / '+jobs.length+' · страницы по 10 карточек');await showPage();}
$('previous').onclick=()=>{page--;showPage();};$('next').onclick=()=>{page++;showPage();};$('saved-collections').onchange=async e=>{if(e.target.value){page=0;try{await loadRun(e.target.value);}catch(err){text('launch-status',err.message);}}};
async function studies(){const all=await api('/api/studies');$('saved-collections').replaceChildren(node('option','Сохранённые коллекции'),...all.runs.map(r=>{const o=node('option',r.name);o.value=r.id;return o;}));$('saved-collections').firstChild.value='';if(all.runs.length){const id=all.runs.some(r=>r.id===runId)?runId:all.runs.find(r=>r.mode==='imported-v9')?.id||all.runs[0].id;await loadRun(id);$('saved-collections').value=id;}}
const wait=()=>new Promise(resolve=>setTimeout(resolve,5000));
async function launch(){if(busy)return;busy=true;$('launch').disabled=true;$('collection-name').disabled=true;$('producer-wishes').disabled=true;try{if(!ready)throw Error('API генерации пока не настроен. История и тест доступны во вкладках сверху.');const draft=collectionBrief($('collection-name').value,$('producer-wishes').value);plannerPayload(draft);saved.pending||={plannerKey:crypto.randomUUID(),runKey:crypto.randomUUID(),name:draft.collection_name,wishes:draft.producer_comment};const p=saved.pending;persist();text('launch-status','Планируем 10 объектов…');if(!p.planId){const r=await api('/api/plan-live',{...plannerPayload(draft),requestId:p.plannerKey,approval:'I approve one paid planner attempt'});p.planId=r.requestId;persist();}let plan;for(let i=0;i<120;i++){const r=await api('/api/planner?id='+encodeURIComponent(p.planId));if(r.result?.validation_error)throw Error('План не прошёл проверку: '+r.result.validation_error);if(r.result?.plan){plan=r.result.plan;break;}if(['failed','unknown','rejected','invalid','blocked','cost_bound_exceeded'].includes(r.status))throw Error('План остановлен: '+r.status+'. Платная попытка не повторяется.');await wait();}if(!plan)throw Error('План ещё не готов. Повторное нажатие проверит эту же попытку.');const approved=plannedCollection(draft,plan);text('launch-status','Создаём 10 карточек…');if(!p.runId){const r=await api('/api/runs',{...imagePayload(approved),requestId:p.runKey,mode:'live',approval:'I approve one paid attempt per object'});p.runId=r.runId;saved.runId=r.runId;persist();}for(let i=0;i<120;i++){await loadRun(p.runId);if(jobs.every(j=>['complete','failed','unknown'].includes(j.status)))break;text('launch-status','Готово '+jobs.filter(j=>j.status==='complete').length+' / 10');await wait();}if(jobs.every(j=>j.status==='complete')){saved.pending=null;persist();}text('launch-status',jobs.every(j=>j.status==='complete')?'Коллекция готова!':'Незавершённые попытки доступны во вкладке «Тест».');await studies();}catch(e){text('launch-status',e.message);}finally{busy=false;$('launch').disabled=false;$('collection-name').disabled=false;$('producer-wishes').disabled=false;}}
$('launch-form').onsubmit=e=>{e.preventDefault();launch();};
await showPage();try{refs=(await api('/api/references')).references;}catch{refs=[];}try{const state=await api('/api/preflight');ready=state.live_enabled&&state.planner?.live&&!state.live_missing?.length&&!state.budget?.live_blockers?.length;if(!ready)text('launch-status','Новая генерация пока недоступна. Готовые коллекции — во вкладке «Тест».');await studies();}catch{text('launch-status','Для сохранённых коллекций войдите как владелец. Новая генерация пока отключена.');}
