import {cardActions} from './card-actions.mjs';
import {plannerStopped,plannerProgress,imageProgress} from './generation-progress.mjs';
import {PAGE_SIZE,collectionBrief,plannedCollection,plannerPayload,imagePayload,categoryFor,blindComparison} from './generator-model.mjs';
const $=id=>document.getElementById(id),key='card-studio-generator/v2';let saved=JSON.parse(localStorage.getItem(key)||'{}'),runId=null,jobs=[],refs=[],page=0,busy=false,ready=false,serial=0,selection=0;const rendered=new Map(),persist=()=>localStorage.setItem(key,JSON.stringify(saved));
async function api(path,body){let r;try{r=await fetch(path,{...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(30000)});}catch(e){throw Error('Не удалось получить ответ сайта · '+path.split('?')[0]+'. Попытка сохранена; повторное нажатие проверит тот же запрос.');}const raw=await r.text();let d;try{d=JSON.parse(raw);}catch{throw Error('Сайт вернул неожиданный ответ вместо JSON · HTTP '+r.status+' · '+path.split('?')[0]+'. Попытка сохранена; повторное нажатие проверит тот же запрос.');}if(!r.ok)throw Error((d.error||String(r.status))+' · '+path.split('?')[0]+(d.diagnostic?' · '+d.diagnostic:''));return d;}

function text(id,value){$(id).textContent=value;}function node(tag,label){const el=document.createElement(tag);if(label)el.textContent=label;return el;}
$('collection-name').value=saved.name||'';$('producer-wishes').value=saved.wishes||'';
for(const id of ['collection-name','producer-wishes'])$(id).oninput=()=>{saved.name=$('collection-name').value;saved.wishes=$('producer-wishes').value;saved.pending=null;persist();};
function placeholder(index,job){const b=node('button');b.type='button';b.className='collection-card placeholder';b.disabled=true;b.append(node('span',String(index+1)),node('span',job?.object_id||'Карточка'));b.firstChild.className='slot-number';b.lastChild.className='card-label';return b;}
async function fullCard(job){if(rendered.has(job.id))return rendered.get(job.id);const image=new Image();image.src='/api/asset?job='+encodeURIComponent(job.id);image.alt=job.name||job.object_id;await image.decode();const card={image,type:categoryFor(job,null)};rendered.set(job.id,card);return card;}
async function showPage(){$('comparison-hint').hidden=false;$('selected-card-info').hidden=true;const ticket=++serial,start=page*PAGE_SIZE,visible=jobs.slice(start,start+PAGE_SIZE);$('card-grid').replaceChildren(...Array.from({length:PAGE_SIZE},(_,i)=>placeholder(start+i,visible[i])));$('previous').disabled=page===0;$('next').disabled=start+PAGE_SIZE>=jobs.length;for(const [i,job] of visible.entries()){if(job.status!=='complete')continue;try{const card=await fullCard(job);if(ticket!==serial)return;const b=node('button');b.type='button';b.className='collection-card';b.setAttribute('aria-label',job.name||job.object_id);b.setAttribute('aria-pressed','false');const art=node('span');art.className='card-art';art.append(card.image);const label=node('span',job.name||job.object_id);label.className='card-label';b.append(art,label);b.onclick=()=>selectCard(job,card,b);const slot=node('div');slot.className='card-slot';const actions=node('div');actions.className='card-actions';const urls=cardActions(runId,job),save=node('a','Сохранить PNG');save.href=urls.download;save.download=urls.filename;save.setAttribute('aria-label','Сохранить '+(job.name||job.object_id)+' в PNG');const test=node('a','В тест');test.href=urls.test;test.setAttribute('aria-label','Открыть '+(job.name||job.object_id)+' в тесте');actions.append(save,test);slot.append(b,actions);$('card-grid').children[i].replaceWith(slot);}catch(e){if(ticket!==serial)return;text('collection-status','Карточка '+job.object_id+': изображение недоступно. '+e.message);}}}
async function selectCard(job,card,button){const ticket=++selection;if(!refs.length){try{refs=(await api('/api/references')).references;}catch{refs=[];}}if(ticket!==selection)return;for(const b of $('card-grid').querySelectorAll('button.collection-card'))b.setAttribute('aria-pressed',String(b===button));$('comparison-hint').hidden=true;$('selected-card-info').hidden=false;text('selected-name','Слепое сравнение');text('selected-type',card.type.category||'Тип уточняется');const items=blindComparison(refs,card.type.category);$('original-cards').replaceChildren(...items.map((item,i)=>{const f=node('figure'),img=node('img');img.src=item.generated?card.image.src:'/api/references/image?id='+encodeURIComponent(item.reference.id);img.alt='Карточка '+(i+1);f.append(img,node('figcaption',String(i+1)));return f;}));text('comparison-status',items.length?'Среди оригиналов этой категории — одна наша карточка. Повторный клик перемешает набор.':'Подходящие оригиналы не найдены. Проверка типа — во вкладке «Тест».');}
const recoveryStatus=node('p');recoveryStatus.id='recovery-status';recoveryStatus.setAttribute('role','status');$('launch-form').append(recoveryStatus);
const diagnosticBox=node('details'),diagnosticTitle=node('summary','Диагностика карточек'),diagnosticList=node('div');diagnosticList.style.maxHeight='160px';diagnosticList.style.overflow='auto';diagnosticBox.append(diagnosticTitle,diagnosticList);$('launch-form').append(diagnosticBox);
const diagnosticLabels={recovery_queued:'Восстановление ответа в очереди',recovery_failed:'Ошибка восстановления сохранённого ответа',requeue_requested:'Отправляем в очередь',requeued:'Очередь приняла задание',worker_received:'Worker получил задание',checking_frozen_input:'Проверяем сохранённый объект',checking_references:'Проверяем референсы',references_checked:'Референсы проверены',provider_starting:'Обращение к API',saving_result:'Сохраняем результат',complete:'Готово',needs_review:'Нужна проверка',failed_before_provider:'Ошибка до API',diagnostic_unavailable:'Диагностика недоступна'};
function showQueueDiagnostics(){diagnosticList.replaceChildren(...jobs.map(j=>{const d=j.queue_diagnostic;return node('p',(j.name||j.object_id)+': '+(d?diagnosticLabels[d.stage]||d.stage:'Нет отметки получения Worker')+(d?.error?' · '+d.error:'')+(d?.at?' · '+new Date(d.at).toLocaleTimeString():''));}));}
async function loadRun(id){runId=id;const d=await api('/api/run?run='+encodeURIComponent(id));jobs=d.jobs;showQueueDiagnostics();page=Math.min(page,Math.max(0,Math.ceil(jobs.length/PAGE_SIZE)-1));text('collection-title',d.run.name);text('collection-status','Готово '+jobs.filter(j=>j.status==='complete').length+' / '+jobs.length+' · страницы по 10 карточек');await showPage();}
$('previous').onclick=()=>{page--;showPage();};$('next').onclick=()=>{page++;showPage();};
const wait=()=>new Promise(resolve=>setTimeout(resolve,5000));
async function launch(){if(busy)return;busy=true;$('launch').disabled=true;$('collection-name').disabled=true;$('producer-wishes').disabled=true;try{text('launch-status','Проверяем подключение…');await refreshReadiness({resume:!!saved.pending?.planId});const draft=collectionBrief($('collection-name').value,$('producer-wishes').value);plannerPayload(draft);saved.pending||={plannerKey:crypto.randomUUID(),runKey:crypto.randomUUID(),name:draft.collection_name,wishes:draft.producer_comment};const p=saved.pending;p.startedAt||=Date.now();persist();text('launch-status',plannerProgress({stage:'queued'},Date.now()-p.startedAt));if(!p.planId){const r=await api('/api/plan-live',{...plannerPayload(draft),requestId:p.plannerKey,approval:'I approve one paid planner attempt'});p.planId=r.requestId;persist();}let plan;for(let i=0;i<120;i++){let r;const started=Date.now(),ticker=setInterval(()=>text('launch-status','Проверяем ответ сайта · '+Math.floor((Date.now()-started)/1000)+' с · платный запрос не повторяется'),1000);try{r=await api('/api/planner?id='+encodeURIComponent(p.planId));}finally{clearInterval(ticker);}text('launch-status',plannerProgress(r,Date.now()-p.startedAt));if(r.result?.validation_error)throw Error('План не прошёл проверку: '+r.result.validation_error);if(r.result?.plan){plan=r.result.plan;break;}if(r.error?.startsWith('Invalid redirect value, must be one of')){const recovery=await api('/api/planner-recover',{requestId:p.planId});if(recovery.not_sent){saved.pending=null;persist();throw Error('Запрос не был отправлен в API. Резерв снят; нажмите ЗАПУСТИТЬ для новой попытки.');}}if(plannerStopped.has(r.status)||plannerStopped.has(r.stage))throw Error('План остановлен: '+(r.error||r.stage||r.status)+'. Платная попытка не повторяется.');await wait();}if(!plan)throw Error('План ещё не готов. Повторное нажатие проверит эту же попытку.');const approved=plannedCollection(draft,plan);text('launch-status','2/3 · План готов. Отправляем 10 карточек в очередь…');if(!p.runId){const r=await api('/api/runs',{...imagePayload(approved),requestId:p.runKey,planner_request_id:p.planId,mode:'live',approval:'I approve one paid attempt per object'});p.runId=r.runId;saved.runId=r.runId;persist();}for(let i=0;i<120;i++){await loadRun(p.runId);if(jobs.every(j=>j.status==='complete'||plannerStopped.has(j.status)))break;text('launch-status',imageProgress(jobs));await wait();}if(jobs.every(j=>j.status==='complete')){saved.pending=null;persist();}text('launch-status',jobs.every(j=>j.status==='complete')?'3/3 · 10/10 карточек готовы. Вся попытка автоматически сохранена в архиве.':'Незавершённые попытки доступны во вкладке «Тест».');}catch(e){text('launch-status',e.message);}finally{busy=false;$('launch').disabled=false;$('collection-name').disabled=false;$('producer-wishes').disabled=false;}}
$('launch-form').onsubmit=e=>{e.preventDefault();launch();};
async function refreshReadiness({resume=false}={}){const state=await api('/api/preflight');const reasons=[...(state.missing||[]),...(state.live_missing||[]),...(state.planner?.missing||[]),...(state.budget?.live_blockers||[]).filter(reason=>!resume||reason!=='attempt_billing_reconciliation_required')];if(!state.live_enabled)reasons.push('Генерация отключена');if(!state.planner?.live)reasons.push('Планировщик отключён');if(state.planner?.ready===false&&!state.planner.missing?.length)reasons.push('Планировщик не готов');ready=reasons.length===0;if(!ready)throw Error('Запуск недоступен: '+[...new Set(reasons)].join(', '));return state;}
await showPage();text('launch-status','Проверяем подключение…');try{await refreshReadiness();text('launch-status','API готов. Укажите коллекцию и нажмите ЗАПУСТИТЬ.');}catch(e){text('launch-status',e.message);}
try{refs=(await api('/api/references')).references;}catch{refs=[];}
try{}catch(e){text('collection-status','Не удалось загрузить сохранённые коллекции: '+e.message);}

async function showRecoveryButtons(){try{const state=await api('/api/preflight');if(state.role!=='owner')return;const data=await api('/api/studies');for(const attempt of (data.attempts||[]).filter(a=>a.receipt_key&&a.job_id.startsWith('run_')&&a.status!=='complete')){const button=node('button','Восстановить сохранённый ответ');button.type='button';button.onclick=async()=>{if(busy)return;busy=true;button.disabled=true;$('launch').disabled=true;try{const result=await api('/api/recover',{jobId:attempt.job_id});recoveryStatus.textContent='Сохранённый ответ отправлен на обработку. Новых вызовов API: '+result.provider_calls+'.';const run=(data.runs||[]).find(r=>attempt.job_id.startsWith(r.id+'_'));if(run)for(let i=0;i<24;i++){await loadRun(run.id);const job=jobs.find(j=>j.id===attempt.job_id);text('launch-status','Восстанавливаем готовое изображение: '+(diagnosticLabels[job?.queue_diagnostic?.stage]||job?.status||'проверяем'));if(job?.status==='complete'){recoveryStatus.textContent='Изображение восстановлено и сохранено. API генерации повторно не вызывался.';button.remove();break;}if(job?.queue_diagnostic?.stage==='recovery_failed')break;await wait();}}catch(e){recoveryStatus.textContent=e.message;}finally{busy=false;button.disabled=false;$('launch').disabled=false;}};$('launch-form').append(button);}for(const run of (data.runs||[]).filter(r=>r.mode==='live'&&r.complete<r.total)){const button=node('button','Продолжить «'+run.name+'»');button.type='button';button.className=$('launch').className;button.onclick=async()=>{if(busy)return;busy=true;button.disabled=true;$('launch').disabled=true;try{text('launch-status','Восстанавливаем очередь сохранённой коллекции…');const recovered=await api('/api/requeue-run',{runId:run.id});recoveryStatus.textContent='Восстановление: очередь приняла '+recovered.sent+' заданий. Планировщик не повторяется.';for(let i=0;i<120;i++){await loadRun(run.id);const received=jobs.filter(j=>j.queue_diagnostic&&!['requeued','requeue_requested'].includes(j.queue_diagnostic.stage)).length;text('launch-status',imageProgress(jobs,jobs.length)+' · получено Worker: '+received+'/'+jobs.length);if(i>=12&&received===0){text('launch-status','За минуту нет отметки получения Worker. Ответ восстановления сохранён ниже; откройте диагностику карточек.');break;}if(jobs.every(j=>j.status==='complete'||plannerStopped.has(j.status)))break;await wait();}if(jobs.every(j=>j.status==='complete')){text('launch-status','Все карточки готовы. Попытка сохранена в истории.');button.remove();}}catch(e){text('launch-status',e.message);}finally{busy=false;button.disabled=false;$('launch').disabled=false;}};$('launch-form').append(button);}}catch(e){text('launch-status','Не удалось проверить сохранённые попытки: '+e.message);}}
await showRecoveryButtons();

const publicDiagnosticBox=node('details'),publicDiagnosticTitle=node('summary','Диагностика обработки — доступна всем'),publicDiagnosticList=node('div');publicDiagnosticList.style.maxHeight='160px';publicDiagnosticList.style.overflow='auto';publicDiagnosticBox.append(publicDiagnosticTitle,publicDiagnosticList);$('launch-form').append(publicDiagnosticBox);
async function updatePublicDiagnostics(){try{const d=await api('/api/generation-status');publicDiagnosticList.replaceChildren(...(d.cards||[]).map(c=>node('p','Карточка '+c.number+': '+(c.stage==='no_worker_receipt'?'Нет отметки получения Worker':diagnosticLabels[c.stage]||c.stage)+(c.reason?' · '+c.reason:'')+(c.at?' · '+new Date(c.at).toLocaleTimeString():''))));if(!d.cards?.length)publicDiagnosticList.textContent='Пока нет попыток генерации.';}catch(e){publicDiagnosticList.textContent='Диагностика недоступна: '+e.message;}}
publicDiagnosticBox.addEventListener('toggle',()=>{if(publicDiagnosticBox.open)updatePublicDiagnostics();});await updatePublicDiagnostics();setInterval(()=>{if(publicDiagnosticBox.open)updatePublicDiagnostics();},10000);
