/* Site assembly policy. Immutable v9 package and historical choices remain auditable. */
const AssemblyV10={version:'composition-v10/1',profiles:{concentric_rings:{core:.38,tail:.16,strength:.85},empty:{core:.38,tail:.16,strength:.85},radial_rays:{core:.24,tail:.48,strength:1},soft:{core:0,tail:1.05,strength:.28}},scaleTarget:{width:.78,height:.76}};
const assemblySmooth=t=>{t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)},assemblyMod=(x,p)=>((x%p)+p)%p;
function assemblyProfile(){const f=recipe().family;return !state.pattern.visible?AssemblyV10.profiles.empty:AssemblyV10.profiles[f]||AssemblyV10.profiles.soft;}
ContinuousField.value=function(x,y,w,h,g){const p=assemblyProfile(),dx=(x/w-g.focusX)*2/(g.axisX||1),dy=(y/h-g.focusY)*2/(g.axisY||1),r=Math.hypot(dx,dy)/Math.max(.2,g.spread||1);return 1-assemblySmooth((r-p.core)/p.tail);};
const assemblyBackground=background;background=function(w,h){const previous=state.gradient;state.gradient={...previous,mode:'broad',saturation:1,strength:assemblyProfile().strength};try{return assemblyBackground(w,h)}finally{state.gradient=previous}};
const assemblyMask=makeMask;
makeMask=function(id,w=430,h=480,p=state.pattern){const m=DATA.geometry.measurements.find(x=>x.id+'/'+x.family===id),f=m.family,g=m.geometry,c=canvas(w,h),ctx=c.getContext('2d'),factor=p.density/p.scale,angle=(p.rotation||0)*Math.PI/180,co=Math.cos(angle),si=Math.sin(angle),tile=ctx.createImageData(w,h),d=tile.data;
 if(f.startsWith('motif_')){ctx.save();ctx.scale(w/430,h/480);ctx.translate(215+p.offsetX/2,240+p.offsetY/2);ctx.rotate(angle);const scale=p.scale/p.density;ctx.scale(scale,scale);ctx.translate(-215,-240);const box=g.motifBoxes[0].xywhPx,px=g.pitchPx?.[0]||130,py=g.pitchPx?.[1]||125,reach=Math.ceil(Math.hypot(430,480)/Math.max(.1,scale)/Math.min(px,py))+4;for(let row=-reach;row<=reach;row++)for(let col=-reach;col<=reach;col++){const b=g.motifBoxes[assemblyMod(row*7+col,g.motifBoxes.length)].xywhPx;ctx.save();ctx.translate(box[0]+col*px+(assemblyMod(row,2)?g.alternatingRowOffsetPx||px*.35:0),box[1]+row*py);glyph(ctx,f,b[2],b[3],assemblyMod(row+col,2),p.thickness);ctx.restore()}ctx.restore();return c;}
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const dx=(x+.5)*430/w-215-p.offsetX/2,dy=(y+.5)*480/h-240-p.offsetY/2,u=(dx*co+dy*si)*factor,v=(-dx*si+dy*co)*factor,rad=Math.hypot(((x+.5)/w-p.originX)*430*(g.xScale||1),((y+.5)/h-p.originY)*480)*factor;let on=0;
 if(f==='concentric_rings'){const bands=g.bands||[],period=bands.length>1?((bands[1].innerOverWidth+bands[1].outerOverWidth)-(bands[0].innerOverWidth+bands[0].outerOverWidth))*215:86,width=(bands[0]?bands[0].outerOverWidth-bands[0].innerOverWidth:.1)*430*p.thickness;on=assemblyMod(rad,Math.max(15,period))<Math.min(period*.8,width);}
 else if(f==='radial_rays'){const n=Math.max(2,Math.round((g.fullTurnLightRayCount?.[0]||9)*factor));on=assemblyMod(Math.atan2((y+.5)/h-p.originY,((x+.5)/w-p.originX)*(g.angularXScale||1))-angle,Math.PI*2/n)<Math.PI/n*p.thickness;}
 else if(f==='vertical_stripes'||f==='diagonal_stripes'){const a=(f==='diagonal_stripes'?(g.normalAnglesDegrees?.[0]||49):0)*Math.PI/180,normal=u*Math.cos(a)+v*Math.sin(a),period=(g.fullPitchOverWidth||g.pitchOverWidthApprox||.24)*430;on=assemblyMod(normal,period)<period*Math.min(.8,.5*p.thickness);}
 else if(f==='square_checker'||f==='diamond_checks'){const cell=(g.cellSizePx?.[0]||g.normalGridPitchOverWidth?.[0]*430||76),a=f==='diamond_checks'?Math.PI/4:0,U=u*Math.cos(a)+v*Math.sin(a),V=-u*Math.sin(a)+v*Math.cos(a);on=assemblyMod(Math.floor(U/cell)+Math.floor(V/cell),2)===0;}
 else if(f==='wave_bands'||f==='curved_bands_ambiguous'){on=assemblyMod(v+35*Math.sin(u/105),100)<48*p.thickness;}
 else if(f==='spiral_swirl'){on=assemblyMod(Math.atan2(v,u)+Math.hypot(u,v)/130,Math.PI/3)<Math.PI/6*p.thickness;}
 else return assemblyMask(id,w,h,p);
 const i=(y*w+x)*4;d[i]=d[i+1]=d[i+2]=255;d[i+3]=on?255:0;}
 ctx.putImageData(tile,0,0);return c;};
patternLayer=function(w,h){const c=canvas(w,h);if(!state.pattern.visible||!isRecipe(recipe()))return c;const mask=makeMask(state.recipe,w,h).getContext('2d').getImageData(0,0,w,h).data,bg=background(w,h).getContext('2d').getImageData(0,0,w,h),d=bg.data,amount=Math.max(.3,Math.abs(state.pattern.contrast||0)),sign=state.pattern.contrast<0?-1:1,delta=(18+12*amount)*sign;
 for(let i=0;i<d.length;i+=4){const max=Math.max(d[i],d[i+1],d[i+2]),min=Math.min(d[i],d[i+1],d[i+2]),mean=(max+min)/2;for(let k=0;k<3;k++)d[i+k]=Math.max(0,Math.min(255,mean+(d[i+k]-mean)*1.08+delta));d[i+3]=Math.round(mask[i+3]*(state.pattern.opacity===0?0:Math.max(.65,state.pattern.opacity)));}c.getContext('2d').putImageData(bg,0,0);return c;};
const assemblyAxisCache=new WeakMap();function assemblyAxis(image){if(assemblyAxisCache.has(image))return assemblyAxisCache.get(image);const c=canvas(86,96);c.getContext('2d').drawImage(image,0,0,86,96);const d=c.getContext('2d').getImageData(0,0,86,96).data;let n=0,sx=0,sy=0,xx=0,xy=0,yy=0;for(let y=0;y<96;y++)for(let x=0;x<86;x++)if(d[(y*86+x)*4+3]>128){n++;sx+=x;sy+=y;xx+=x*x;xy+=x*y;yy+=y*y;}if(!n)return null;const a=xx/n-(sx/n)**2,b=xy/n-sx*sy/n**2,cov=yy/n-(sy/n)**2,tr=a+cov,gap=Math.hypot(a-cov,2*b),axis={angle:.5*Math.atan2(2*b,a-cov)*180/Math.PI,elongated:(tr+gap)/Math.max(.01,tr-gap)>1.7};assemblyAxisCache.set(image,axis);return axis;}
const assemblyCompose=compose;compose=function(w=430,h=480){const previous=state,copy=clone(state),a=assets.get(copy.layers.object),axis=a?assemblyAxis(a.image):null,f=recipe().family;if(axis?.elongated&&['vertical_stripes','diagonal_stripes','wave_bands','curved_bands_ambiguous'].includes(f)){const base=f==='vertical_stripes'?90:f==='diagonal_stripes'?(recipe().geometry.edgeAngleDegreesFromX||-41):0;let line=base+copy.pattern.rotation,difference=Math.abs(assemblyMod(line-axis.angle+90,180)-90);if(difference<45)copy.pattern.rotation=assemblyMod(axis.angle+90-base+180,360)-180;}state=copy;try{return assemblyCompose(w,h)}finally{state=previous}};
const assemblyManifest=manifest;manifest=function(){return {...assemblyManifest(),assemblyPolicy:{...AssemblyV10,profile:assemblyProfile(),geometry:'procedural infinite continuation; user-requested assembly approximation',contrast:'minimum visible separation; saturated same-hue patterns',orientation:'elongated silhouette axis avoidance'}}};
Object.assign(reviewEngine,{compose,manifest,background,patternLayer,makeMask,compositionPolicy:AssemblyV10});render();
