import {C2_SURFACE_POLICY,surfaceHorizon,projectedSubjectShadow,surfacePalette,subjectLighting} from './surface-policy.mjs';
/* Public bridge; calibration stays in the authenticated private package. */
export async function editorEngine(){
 let frame=document.getElementById('private-engine');if(!frame){frame=document.createElement('iframe');frame.id='private-engine';frame.src='/editor/';frame.hidden=true;document.body.append(frame);}
 for(let i=0;i<100;i++){const engine=frame.contentWindow?.reviewEngine;if(engine?.compositionPolicy)return engine;await new Promise(r=>setTimeout(r,100));}throw Error('Private v9 editor unavailable; verify package and access.');
}
export async function calibratedAlternatives(job,image,hash){
 image=assemblyObject(image,job);
 const e=await editorEngine(),object=e.canvas(860,960);object.getContext('2d').drawImage(image,0,0);const s=e.getState();s.layers={background:null,surface:null,object:null,finishing:null};s.theme={collectionBrief:'',topics:[],manualMotifOverride:false};Object.assign(s.gradient,{mode:'broad',angle:0,axisX:1,axisY:1,coreRadius:.14,falloffRadius:1.6,focusX:.5,focusY:.5,spread:1,strength:1});e.setState(s);e.assets.set(job.id,{id:job.id,name:job.object_id,sha256:hash,image,width:860,height:960});
 const choices=e.autoMatch(object);if(choices.selected.length!==3)throw Error('v9 needs three eligible candidates');const source=object.getContext('2d').getImageData(0,0,860,960).data,alternatives=[];
 for(const [i,row]of choices.selected.entries()){row.config.layers.object=job.id;e.setState(row.config);if(job.category==='C2')await installPlane(e,row.config,job,image);e.setState(row.config);const canvas=e.compose(860,960),pixels=canvas.getContext('2d').getImageData(0,0,860,960).data;let objectMismatch=0,nonopaque=0;for(let n=0;n<pixels.length;n+=4){nonopaque+=pixels[n+3]!==255;if(source[n+3]===255)objectMismatch+=pixels[n]!==source[n]||pixels[n+1]!==source[n+1]||pixels[n+2]!==source[n+2];}if(objectMismatch||nonopaque)throw Error('Foreground protection QA failed');alternatives.push({id:'candidate-'+i,config:{...e.manifest(),objectAssembly:{version:'c1-c2-silhouette-fit/v2',surfacePolicy:job.category==='C2'?C2_SURFACE_POLICY:null,lightingOverride:job.lightDirection||'auto',maxWidth:.78,maxHeight:.76,sourceUnchanged:true}},features:row.assessment,qa:{width:860,height:960,objectMismatch,nonopaque},semanticReview:'unreviewed'});}return alternatives;
}
export async function drawCalibrated(canvas,alternative,job,image,hash){image=assemblyObject(image,job);const e=await editorEngine(),assetId=alternative.config.layers?.object||job.id;e.assets.set(assetId,{id:assetId,name:job.object_id,sha256:hash,image,width:860,height:960});const config=structuredClone(alternative.config);if(job.category==='C2')await installPlane(e,config,job,image);e.setState(config);canvas.getContext('2d').drawImage(e.compose(860,960),0,0);}

async function installPlane(e,config,job,image){
 if(job.generation?.surface_mode==='generated')return;
 const id=job.id+'-plane';if(config.layers?.surface&&config.layers.surface!==id)return;
 const source=e.canvas(860,960);source.getContext('2d').drawImage(image,0,0);const pixels=source.getContext('2d').getImageData(0,0,860,960).data;let bottom=480;for(let y=0;y<960;y++)for(let x=0;x<860;x++)if(pixels[(y*860+x)*4+3]>30)bottom=Math.max(bottom,y);
 const plane=e.canvas(860,960),ctx=plane.getContext('2d'),horizon=surfaceHorizon(960),gradient=ctx.createLinearGradient(0,horizon,0,960);const bg=Array.from(e.background(860,960).getContext('2d').getImageData(0,0,1,1).data).slice(0,3),palette=surfacePalette(e.manifest().palettePolicy?.selection,bg),top=surfaceRGB(palette.h+palette.shift,Math.max(.42,palette.s-.10*.85),1),end=surfaceRGB(palette.h,Math.max(.42,palette.s),Math.max(.86,palette.v));gradient.addColorStop(0,'rgb('+top.join(',')+')');gradient.addColorStop(1,'rgb('+end.join(',')+')');ctx.fillStyle=gradient;ctx.fillRect(0,horizon,860,960-horizon);const shadowMap=job.generation?.shadow_mode==='generated-alpha'?new Float32Array(860*960):projectedSubjectShadow(pixels,860,960,{scale:1,dx:0,dy:0},subjectLighting(pixels,860,960,config.objectAssembly?.lightingOverride||job.lightDirection||'auto')),shadow=ctx.getImageData(0,horizon,860,960-horizon);for(let y=horizon;y<960;y++)for(let x=0;x<860;x++){const a=shadowMap[y*860+x],p=((y-horizon)*860+x)*4;for(let k=0;k<3;k++)shadow.data[p+k]*=1-a;}ctx.putImageData(shadow,0,horizon);
 const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(plane.toDataURL('image/png')))),n=>n.toString(16).padStart(2,'0')).join('');e.assets.set(id,{id,name:'C2 · procedural full-width plane',sha256:hash,image:plane,width:860,height:960});config.layers.surface=id;
}

export function assemblyObject(image,job){
 const source=document.createElement('canvas');source.width=860;source.height=960;source.getContext('2d').drawImage(image,0,0,860,960);const data=source.getContext('2d').getImageData(0,0,860,960).data;let x0=860,y0=960,x1=-1,y1=-1,opaque=0;for(let y=0;y<960;y++)for(let x=0;x<860;x++){const a=data[(y*860+x)*4+3];if(a>245)opaque++;if(a>(job.generation?.shadow_mode==='generated-alpha'?199:30)){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}}if(job.generation?.surface_mode==='generated')return source;const isolated=!job.category&&opaque/(860*960)<.98&&x0>17&&x1<843;if(!['C1','C2'].includes(job.category)&&!isolated||x1<x0)return source;const scale=Math.min(1,.78*860/(x1-x0+1),.76*960/(y1-y0+1));if(scale>.999&&job.category!=='C2')return source;const fitted=document.createElement('canvas');fitted.width=860;fitted.height=960;const ctx=fitted.getContext('2d');ctx.imageSmoothingQuality='high';ctx.drawImage(source,(860-(x0+x1+1)*scale)/2,(job.category==='C2'?960*C2_SURFACE_POLICY.objectBottomFraction-(y1+1)*scale:(960-(y0+y1+1)*scale)/2),860*scale,960*scale);return fitted;
}


function surfaceRGB(h,s,v){h=((h%360)+360)%360/60;const c=v*s,x=c*(1-Math.abs(h%2-1)),m=v-c,a=h<1?[c,x,0]:h<2?[x,c,0]:h<3?[0,c,x]:h<4?[0,x,c]:h<5?[x,0,c]:[c,0,x];return a.map(n=>Math.round((n+m)*255));}
