import {runAccess} from './roles.mjs';
import {sha} from './provider.mjs';
const one=(env,sql,...args)=>env.DB.prepare(sql).bind(...args).first();
const all=async(env,sql,...args)=>(await env.DB.prepare(sql).bind(...args).all()).results;
async function artifact(env,key){const o=await env.ARTIFACTS.get(key);if(!o)throw Error('Missing attempt artifact');return o.json();}
export async function attemptPacket(env,auth,runId){
 const run=await runAccess(env,auth,runId),source=await env.ARTIFACTS.get(run.frozen_key);if(!source)throw Error('Missing frozen run');const raw=await source.text();if(await sha(raw)!==run.frozen_sha)throw Error('Frozen run integrity failure');const frozen=JSON.parse(raw);
 const jobs=await all(env,'SELECT j.*,a.status attempt_status,a.actual,a.reservation,a.error,a.created_at attempt_created_at,r.manifest_key,r.final_key,c.payload alternatives,ch.payload choice FROM jobs j LEFT JOIN attempts a ON a.job_id=j.id LEFT JOIN results r ON r.job_id=j.id LEFT JOIN candidates c ON c.job_id=j.id LEFT JOIN choices_v2 ch ON ch.job_id=j.id AND ch.principal_id=? WHERE j.run_id=?',auth.principalId,runId);
 let planner=null;if(frozen.planner_request_id){const p=await one(env,'SELECT * FROM planner_requests WHERE id=?',frozen.planner_request_id);if(p&&(auth.role==='owner'||p.principal_id===auth.principalId))planner={id:p.id,status:p.status,input:await artifact(env,p.input_key),result:p.result_key?await artifact(env,p.result_key):null};}
 const cards=await Promise.all(jobs.map(async job=>{let result=null,artifact_error=null;if(job.manifest_key)try{result=await artifact(env,job.manifest_key);}catch(e){artifact_error=e.message;}return {job_id:job.id,object_id:job.object_id,status:job.status,attempt_status:job.attempt_status||null,actual_cost_nanodollars:job.actual??null,reservation_nanodollars:job.reservation??null,error:job.error?String(job.error).split(env.OPENAI_API_KEY||'__NO_KEY__').join('[redacted]'):null,object:frozen.objects.find(o=>o.object_id===job.object_id)||null,image_url:job.status==='complete'?'/api/asset?job='+encodeURIComponent(job.id):null,test_url:'/studio/index.html?run='+encodeURIComponent(runId)+'&job='+encodeURIComponent(job.id),result,artifact_error,alternatives:job.alternatives?JSON.parse(job.alternatives):null,choice:job.choice?JSON.parse(job.choice):null};}));
 return {version:'generation-attempt/v1',id:run.id,name:run.name,created_at:run.created_at,mode:run.mode,expected_cards:frozen.objects.length,completed_cards:cards.filter(c=>c.status==='complete').length,storage:'Automatically persisted run, immutable prompts, image results, decisions and provider journal',frozen,planner,cards,pix:{status:'connection_required',recipient:'Пикс · ChatGPT dot',packet_url:'/api/attempt-packet?run='+encodeURIComponent(runId),instruction:'Опиши всю попытку целиком: зачем создавали коллекцию, какие пожелания продюсера и гипотезы были заданы, почему выбирали эти предметы, материалы, фоны и узоры, что получилось по каждой карточке, какие проверки и ошибки зафиксированы, что менять дальше. Разделяй зафиксированные причины и свои предположения. Не называй попытку успешной без результатов проверки. Используй все карточки, включая неуспешные, а не один выбранный пример.'},public:false};
}
