import fs from 'node:fs';import {spawn} from 'node:child_process';const root=new URL('./',import.meta.url),checks=[],check=(n,p)=>{checks.push({name:n,pass:!!p});if(!p)throw Error(n)};
spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--disable-gpu','--remote-debugging-port=9383','--user-data-dir='+new URL('../qa-output/edge-html/',root).pathname.replace(/^\/(\w:)/,'$1'),'--no-first-run','about:blank'],{stdio:'ignore',windowsHide:true});let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch('http://127.0.0.1:9383/json')).json();break}catch{await new Promise(r=>setTimeout(r,150))}}const ws=new WebSocket(tabs.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();ws.onmessage=e=>{const d=JSON.parse(e.data);if(pending.has(d.id)){pending.get(d.id)(d);pending.delete(d.id)}};const send=(method,params={})=>new Promise(r=>{pending.set(++id,r);ws.send(JSON.stringify({id,method,params}))});async function ev(expression){const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.result.exceptionDetails)throw Error(JSON.stringify(r.result.exceptionDetails));return r.result.result.value}async function until(expr){for(let i=0;i<60;i++){if(await ev(expr))return;await new Promise(r=>setTimeout(r,150))}throw Error('timeout '+expr)}
try{
 await send('Page.navigate',{url:'http://127.0.0.1:5190/'});await until("document.getElementById('briefs')?.value.includes('Synthetic shape')");
 await ev("document.getElementById('create').requestSubmit()");await until("document.getElementById('created').textContent.startsWith('Запущен')");
 const run=await ev("document.getElementById('created').textContent.split(' ')[1]");check('HTML brief form launches mock run',run.startsWith('mock-'));
 let ready=false;for(let i=0;i<360;i++){const state=await(await fetch('http://127.0.0.1:5190/api/studies')).json();if(state.runs.find(r=>r.id===run)?.ready===20){ready=true;break}const error=await ev("typeof failed==='undefined'?null:failed");if(error)throw Error(error);await new Promise(r=>setTimeout(r,500))}check('new HTML run auto-registers 20 objects without redeploy',ready);
 const result=await(await fetch('http://127.0.0.1:5190/api/run?run='+run)).json();check('20 per-image successes',result.objects.length===20&&result.objects.every(o=>o.status==='complete'));
 const html=await(await fetch('http://127.0.0.1:5190/assets/'+run+'/results.html')).text();check('standalone results HTML has 20 inline PNGs and no scripts',(html.match(/data:image\/png;base64/g)||[]).length===20&&!html.includes('<script'));
 await send('Page.navigate',{url:'http://127.0.0.1:5190/assets/'+run+'/results.html'});await until('document.images.length===20 && [...document.images].every(i=>i.complete&&i.naturalWidth===860)');check('standalone results gallery renders',true);
 fs.writeFileSync(new URL('../qa-output/html-report.json',root),JSON.stringify({checks,run,paidCalls:0},null,2));console.log(JSON.stringify({checks,run,paidCalls:0}));
}finally{await send('Browser.close');ws.close()}
