import fs from 'node:fs';import {spawn} from 'node:child_process';const root=new URL('./',import.meta.url),checks=[],check=(n,p)=>{checks.push({name:n,pass:!!p});if(!p)throw Error(n)};
spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--disable-gpu','--remote-debugging-port=9382','--user-data-dir='+new URL('../qa-output/edge-pattern/',root).pathname.replace(/^\/(\w:)/,'$1'),'--no-first-run','about:blank'],{stdio:'ignore',windowsHide:true});let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch('http://127.0.0.1:9382/json')).json();break}catch{await new Promise(r=>setTimeout(r,150))}}const ws=new WebSocket(tabs.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();ws.onmessage=e=>{const d=JSON.parse(e.data);if(pending.has(d.id)){pending.get(d.id)(d);pending.delete(d.id)}};const send=(method,params={})=>new Promise(r=>{pending.set(++id,r);ws.send(JSON.stringify({id,method,params}))});async function ev(expression){const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.result.exceptionDetails)throw Error(JSON.stringify(r.result.exceptionDetails));return r.result.result.value}async function until(expr){for(let i=0;i<60;i++){if(await ev(expr))return;await new Promise(r=>setTimeout(r,150))}throw Error('timeout '+expr)}
try{
 const measurements={};
 for(const version of ['v9','v10']){
  await send('Page.navigate',{url:'http://127.0.0.1:5190/measured-editor-'+version+'.html'});await until('!!window.reviewEngine?.coreFalloffPolicy');
  if(version==='v9')await ev("new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='/pattern-qa.js';s.onload=resolve;s.onerror=reject;document.body.append(s)})");
  measurements[version]=await ev("(()=>{const e=reviewEngine,s=e.getState();s.recipe='R07C08/vertical_stripes';s.pattern.scale=40;s.pattern.density=180;s.pattern.rotation=0;s.pattern.offsetX=0;s.pattern.offsetY=0;s.pattern.opacity=.65;e.setState(s);return measurePattern(e)})()");
 }
 check('v9 repeating-stripe cutoff reproduced before object compositing',measurements.v9.marginCoverage[0]===0&&measurements.v9.marginCoverage[1]===0);
 check('v10 continues stripes into both card margins',measurements.v10.marginCoverage[0]>.05&&measurements.v10.marginCoverage[1]>.05);
 check('transparent stripe gaps remain',measurements.v10.maskCoverage>.05&&measurements.v10.maskCoverage<.95);
 const alpha=await ev("(()=>{const e=reviewEngine,s=e.getState();s.pattern.opacity=0;e.setState(s);return measurePattern(e)})()");check('zero opacity explicit and measured',alpha.visibleCoverage===0&&alpha.meanVisibleRGBDelta===0);
 const occlusion=await ev(`(()=>{const e=reviewEngine,s=e.getState();s.pattern.opacity=.7;const a=e.canvas(860,960),g=a.getContext('2d');g.fillStyle='rgb(200,50,80)';g.fillRect(200,200,400,500);g.clearRect(300,300,100,100);e.assets.set('qa-object',{id:'qa-object',name:'synthetic',image:a,sha256:'mock'});s.layers={background:null,surface:null,object:null,finishing:null};e.setState(s);const before=e.compose(860,960),base=before.getContext('2d').getImageData(0,0,860,960).data;s.layers.object='qa-object';e.setState(s);const after=e.compose(860,960).getContext('2d').getImageData(0,0,860,960).data;const pixel=(d,x,y)=>[...d.slice((y*860+x)*4,(y*860+x)*4+4)];return{opaque:pixel(after,250,250),hole:pixel(after,350,350),expectedHole:pixel(base,350,350)}})()`);
 check('opaque object blocks pattern',JSON.stringify(occlusion.opaque)==='[200,50,80,255]');check('transparent hole shows unchanged underlying composition',JSON.stringify(occlusion.hole)===JSON.stringify(occlusion.expectedHole));
 fs.writeFileSync(new URL('../qa-output/pattern-report.json',root),JSON.stringify({checks,measurements,occlusion},null,2));console.log(JSON.stringify({checks,measurements}));
}finally{await send('Browser.close');ws.close()}
