import assert from 'node:assert/strict';
import {generationContract,generationInstructions} from '../cloudflare/generation-contract.mjs';
import {proceduralCard} from '../cloudflare/procedural-card.mjs';
import {compileObjectPrompt} from '../cloudflare/object-content-policy.mjs';
import {artDirectionRule,ART_DIRECTION_RULE_VERSION} from '../cloudflare/art-direction-policy.mjs';
for(const category of ['C1','C2','C3','C4']){const prompt=compileObjectPrompt({art_direction:'Approved camera and proportions',generalized_rules:'Pinned rules'},'Explicit soil contents',generationContract(category));assert(prompt.startsWith('Approved camera and proportions\n\nPinned rules'));assert(prompt.includes(artDirectionRule),'Global clean-materials rule missing in '+category);assert.match(prompt,/scuffs, scratches/);assert.match(prompt,/Explicitly requested contents such as soil remain recognizable/);}assert.equal(ART_DIRECTION_RULE_VERSION,'art-direction/clean-materials-v1');
const contract=generationContract('C2');assert.equal(contract.background,'transparent');assert.equal(contract.shadow_mode,'generated-alpha');
for(const category of ['C1','C3','C4'])assert.equal(generationContract(category).shadow_mode,undefined);
assert.equal(generationContract('C2','whole_card').shadow_mode,undefined);
const prompt=generationInstructions(contract);assert.match(prompt,/genuine partial alpha/);assert.match(prompt,/bottom 30%/);assert.match(prompt,/adds no second shadow/);assert.match(prompt,/Do NOT generate a floor/);
const width=1000,height=1000,rgba=new Uint8Array(width*height*4);
for(let y=200;y<880;y++)for(let x=250;x<750;x++)rgba.set([20,90,230,255],(y*width+x)*4);
for(let y=880;y<970;y++)for(let x=40;x<500;x++)rgba.set([0,0,0,80],(y*width+x)*4);
const before=rgba.slice(),input={width,height,rgba},settings={shadowMode:'generated-alpha'},card=proceduralCard(input,'C2',settings),disabled=proceduralCard(input,'C2',{...settings,shadow:false});
assert.deepEqual(card.rgba,disabled.rgba,'Editor added a second shadow');assert.deepEqual(rgba,before,'Source PNG pixels changed');
assert.equal(card.composition.objectAssembly.scale,1);assert.equal(card.composition.objectAssembly.widthFraction,.5);assert.equal(card.composition.objectAssembly.heightFraction,.68);
assert.equal(card.composition.surface.shadow.source,'generated-alpha');assert.equal(card.composition.surface.shadow.editorAdded,false);
const blank=rgba.slice();for(let y=880;y<970;y++)for(let x=40;x<500;x++)blank.fill(0,(y*width+x)*4,(y*width+x)*4+4);
const background=proceduralCard({width,height,rgba:blank},'C2',settings),p=(920*width+100)*4;
for(let c=0;c<3;c++)assert(Math.abs(card.rgba[p+c]-background.rgba[p+c]*(1-80/255))<=1,'Partial alpha was flattened onto a white backing');
for(let i=3;i<card.rgba.length;i+=4)assert.equal(card.rgba[i],255);
console.log('PASS C2-only transparent generated-shadow contract; no second shadow; solid-subject sizing excludes shadow; source alpha unchanged; opaque final composition without white backing');
