import {claimPaid,budgetState} from '../cloudflare/budget.mjs';
import {strictSchema} from '../cloudflare/text-planner.mjs';
import {plannerSchema} from '../cloudflare/planner-contract.mjs';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFile } from 'node:fs/promises';
import { createWorker,processJob } from '../cloudflare/worker.mjs';
import { sha,imageRequest,usageCost,IMAGE_MODEL } from '../cloudflare/provider.mjs';
import { mockPNG,decodePNG,finalPNG } from '../cloudflare/png.mjs';
const db=new DatabaseSync(':memory:');db.exec(await readFile(new URL('../cloudflare/schema.sql',import.meta.url),'utf8'));
function statement(sql,args=[]){return {bind(...a){return statement(sql,a);},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};},sql,args};}
const DB={prepare:statement,async batch(items){db.exec('BEGIN');try{const results=[];for(const s of items)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};
class Bucket{constructor(){this.map=new Map();this.fail=null;}async put(k,v){if(this.fail?.(k))throw Error('Injected R2 write failure');this.map.set(k,typeof v==='string'?new TextEncoder().encode(v):new Uint8Array(v));}async get(k){const v=this.map.get(k);return v?{body:new Blob([v]).stream(),arrayBuffer:async()=>v.slice().buffer,text:async()=>new TextDecoder().decode(v),json:async()=>JSON.parse(new TextDecoder().decode(v))}:null;}async head(k){return this.map.has(k)?{}:null;}}
const bucket=new Bucket(),messages=[];
const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk=await crypto.subtle.exportKey('jwk',keys.publicKey);jwk.kid='test';
const b64=x=>Buffer.from(typeof x==='string'?x:JSON.stringify(x)).toString('base64url');
async function jwt(overrides={}){const now=Math.floor(Date.now()/1000),content=b64({alg:'RS256',kid:'test'})+'.'+b64({iss:'https://offline-test.cloudflareaccess.com',aud:['test-aud'],email:'owner'+'@'+'example.invalid',iat:now,exp:now+600,...overrides});return content+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',keys.privateKey,new TextEncoder().encode(content))).toString('base64url');}
const token=await jwt(),env={DB,ARTIFACTS:bucket,IMAGE_JOBS:{async send(body){messages.push(body);}},ASSETS:{async fetch(){return new Response('<html>bootstrap</html>',{headers:{'Content-Type':'text/html'}});}},ACCESS_TEAM_DOMAIN:'https://offline-test.cloudflareaccess.com',ACCESS_AUD:'test-aud',OWNER_EMAIL:'owner'+'@'+'example.invalid',LIVE_GENERATION_ENABLED:'false'};
let providerCalls=0,providerMode='ok';const raw=await mockPNG(864,960);
let textCalls=0;
const worker=createWorker({textProvider:async(env,frozen)=>{textCalls++;return textAnswer(frozen);},authFetch:async()=>Response.json({keys:[jwk]}),provider:async()=>{providerCalls++;if(providerMode==='timeout')throw Error('Injected ambiguous timeout');return {png:raw,usage:{input_tokens:3,input_tokens_details:{text_tokens:1,image_tokens:2},output_tokens:4,total_tokens:7},requestId:'synthetic-request'};}});
async function call(path,body,options={}){return worker.fetch(new Request('https://studio.example.invalid'+path,{method:body?'POST':'GET',headers:{'Cf-Access-Jwt-Assertion':options.token??token,...(body?{'Content-Type':'application/json',Origin:options.origin||'https://studio.example.invalid'}:{})},...(body?{body:JSON.stringify(body)}:{})}),options.env||env);}
async function data(path,body){const r=await call(path,body);const d=await r.json();assert(r.ok,JSON.stringify(d));return d;}
const checks=[];async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
const mail=n=>n+'@'+'example.invalid';env.GUEST_GENERATION_EMAILS=JSON.stringify([mail('guest-a'),mail('guest-b')]);env.REVIEWER_EMAILS=JSON.stringify([mail('reviewer')]);
const ta=await jwt({email:mail('guest-a'),sub:'subject-a'}),tb=await jwt({email:mail('guest-b'),sub:'subject-b'}),tr=await jwt({email:mail('reviewer'),sub:'subject-review'});
const guest=async(path,body,t=ta)=>call(path,body,{token:t});const gd=async(path,body,t=ta)=>{const r=await guest(path,body,t);const d=await r.json();assert(r.ok,JSON.stringify(d));return d;};
const pa=(await gd('/api/preflight')).principalId,pb=(await gd('/api/preflight',null,tb)).principalId,pr=(await gd('/api/preflight',null,tr)).principalId;
let runA,jobA;
await check('verified guest identity, server role and owner-only operations',async()=>{assert.notEqual(pa,pb);assert.equal((await gd('/api/preflight')).role,'generator');assert.equal((await guest('/api/budget')).status,403);assert.equal((await guest('/api/dispatch',{})).status,403);assert.equal((await guest('/api/runs',{objects:[{object_id:'r',brief:'test'}]},tr)).status,403);});
await check('guest creates own study; other guest cannot list/read/alter it',async()=>{runA=await gd('/api/runs',{objects:[{object_id:'a',category:'C1',brief:'test'}],principal_id:'owner',role:'owner'});jobA=(await gd('/api/run?run='+runA.runId)).jobs[0];assert.equal(db.prepare('SELECT principal_id FROM runs WHERE id=?').get(runA.runId).principal_id,pa);assert.equal((await guest('/api/run?run='+runA.runId,null,tb)).status,403);assert.equal((await gd('/api/studies',null,tb)).runs.length,0);assert.equal((await guest('/api/choices',{jobId:jobA.id,eventId:'x',revision:1,action:'none'},tb)).status,403);await worker.queue({messages:[{body:{version:1,jobId:jobA.id},ack(){}}]},env);while(messages.length){const body=messages.shift();await worker.queue({messages:[{body,ack(){}}]},env);}});
await check('guest gets own PNG/info but no raw receipts, frozen prompts or all-reviewer export',async()=>{assert.equal((await guest('/api/asset?job='+jobA.id)).status,200);assert.equal((await guest('/api/image-info?job='+jobA.id)).status,200);assert.equal((await guest('/api/asset?job='+jobA.id+'&kind=manifest')).status,403);assert.equal((await guest('/api/export?run='+runA.runId)).status,403);assert.equal((await guest('/api/asset?job='+jobA.id,null,tb)).status,403);});
await check('three reviewers share a study but retain independent answers/revisions',async()=>{for(const p of [pb,pr])db.prepare('INSERT INTO run_access VALUES (?,?)').run(runA.runId,p);await gd('/api/candidates',{jobId:jobA.id,alternatives:[0,1,2].map(i=>({id:'v'+i,config:{background:'#abc'}}))});for(const[t,selected]of[[ta,'v0'],[tb,'v1'],[tr,'v2']])await gd('/api/choices',{jobId:jobA.id,eventId:'same-client-event',revision:1,action:'select',selected,principal_id:'owner'},t);for(const[t,selected]of[[ta,'v0'],[tb,'v1'],[tr,'v2']]){const j=(await gd('/api/run?run='+runA.runId,null,t)).jobs[0];assert.equal(JSON.parse(j.choice).selected,selected);assert.equal(j.revision,1);}assert.equal(db.prepare('SELECT COUNT(*) n FROM choices_v2').get().n,3);assert.equal((await guest('/api/candidates',{jobId:jobA.id,alternatives:[]},tr)).status,403);});
const sheet=await mockPNG(896,1040),sheetSha=await sha(sheet),ad='Synthetic approved fixture';const ref={version:'reference-pack/v1',model:IMAGE_MODEL,reference_count:50,art_direction_version:'synthetic-v1',art_direction:ad,art_direction_sha256:await sha(ad),sheets:Array.from({length:13},(_,i)=>({key:'references/s'+i+'.png',sha256:sheetSha,count:i===12?2:4}))};for(const s of ref.sheets)await bucket.put(s.key,sheet);const refText=JSON.stringify(ref);await bucket.put('references/m.json',refText);Object.assign(env,{REFERENCE_MANIFEST_KEY:'references/m.json',APPROVED_REFERENCE_MANIFEST_SHA256:await sha(refText),APPROVED_ART_DIRECTION_SHA256:await sha(ad),LIVE_GENERATION_ENABLED:'true',LIVE_PLANNER_ENABLED:'true',OPENAI_API_KEY:'synthetic-not-real',TEXT_PRICE_NANODOLLARS_PER_TOKEN:JSON.stringify({input:10000000,cached:10000000,output:10000000}),TEXT_RESERVATION_NANODOLLARS:'100000000',TEXT_COST_BOUND_EVIDENCE:'synthetic-fixture-only',IMAGE_MAX_COST_NANODOLLARS:'1000000000',IMAGE_COST_BOUND_EVIDENCE:'synthetic-fixture-only'});db.exec('UPDATE budget SET approved=1,ceiling=100000000000');
function fixture(s){if(s.enum)return s.enum[0];if(s.type==='object')return Object.fromEntries(Object.entries(s.properties).map(([k,v])=>[k,fixture(v)]));if(s.type==='array')return [];return 'synthetic';}
function textAnswer(frozen){assert.equal(frozen.input.art_direction_rules.version,'art-direction/clean-materials-v2-reference-color-shadow');assert.match(frozen.input.art_direction_rules.text,/scuffs, scratches/);const schema=strictSchema(plannerSchema),plan=fixture(schema),c=fixture(schema.properties.collections.items),o=fixture(schema.properties.collections.items.properties.objects.items);o.object_id='text-object';c.objects=[o];plan.collections=[c];plan.art_direction_sha256=frozen.input.immutable_art_direction.sha256;plan.art_direction_version=frozen.input.immutable_art_direction.version;return {requestId:'synthetic-text',payload:{status:'completed',usage:{input_tokens:2,output_tokens:8,input_tokens_details:{cached_tokens:0}},output:[{content:[{type:'output_text',text:JSON.stringify(plan)}]}]}};}
await check('guest planner structured output completes once and is isolated by identity',async()=>{const a=await gd('/api/plan-live',{requestId:'same-browser-key',theme:'Toys',approval:'I approve one paid planner attempt'});const b=await gd('/api/plan-live',{requestId:'same-browser-key',theme:'Toys',approval:'I approve one paid planner attempt'},tb);assert.notEqual(a.requestId,b.requestId);await worker.queue({messages:[{body:{version:1,kind:'planner',jobId:a.requestId},ack(){}}]},env);await worker.queue({messages:[{body:{version:1,kind:'planner',jobId:a.requestId},ack(){}}]},env);assert.equal(textCalls,1);const result=await gd('/api/planner?id='+a.requestId);assert.equal(result.status,'complete');assert.equal(result.result.plan.objects.length,1);assert.equal((await guest('/api/planner?id='+a.requestId,null,tb)).status,403);assert.equal((await budgetState(env)).guest_committed,100000000);});
await check('guest image and text use the same lifetime shared ledger',async()=>{const r=await gd('/api/runs',{mode:'live',approval:'I approve one paid attempt per object',objects:[{object_id:'paid',brief:'synthetic'}]},tb),j=(await gd('/api/run?run='+r.runId,null,tb)).jobs[0];await worker.queue({messages:[{body:{version:1,jobId:j.id},ack(){}}]},env);assert.equal(providerCalls,1);assert.equal((await budgetState(env)).guest_committed,100141000);});
await check('historical $1.10 blocks image AND text without erasing reserve',async()=>{db.exec('UPDATE budget SET historical_unknown=1100000000');const a=await guest('/api/plan-live',{requestId:'blocked-history',theme:'Toys',approval:'I approve one paid planner attempt'});assert.equal(a.status,409);const b=await guest('/api/runs',{mode:'live',approval:'I approve one paid attempt per object',objects:[{object_id:'blocked',brief:'x'}]});assert.equal(b.status,409);assert.equal((await budgetState(env)).historical_unknown,1100000000);assert.equal(providerCalls,1);db.exec('UPDATE budget SET historical_unknown=0');});
await check('missing verified bound rejects guest generation before any provider call',async()=>{const prior=env.IMAGE_COST_BOUND_EVIDENCE;delete env.IMAGE_COST_BOUND_EVIDENCE;assert.equal((await guest('/api/runs',{mode:'live',approval:'I approve one paid attempt per object',objects:[{object_id:'no-bound',brief:'x'}]})).status,409);env.IMAGE_COST_BOUND_EVIDENCE=prior;});
await check('atomic concurrent claims share remaining $5 across identities and request kinds',async()=>{db.prepare("INSERT INTO attempts(job_id,mode,status,reservation,actual,created_at,principal_id,budget_scope) VALUES('synthetic-prior','live','complete',?,?,'test',?,'guests-shared')").run(4799859000,4799859000,pa);assert.equal((await budgetState(env)).guest_remaining,100000000);const results=await Promise.all([claimPaid(env,'last-text',100000000,pa),claimPaid(env,'last-image',100000000,pb)]);assert.equal(results.filter(Boolean).length,1);assert.equal((await budgetState(env)).guest_remaining,0);db.exec("UPDATE attempts SET status='complete',actual=reservation WHERE job_id IN ('last-text','last-image')");assert.equal(await claimPaid(env,'new-run-cannot-reset',1,pb),false);});
await check('exhausted shared cap blocks actual planner queue; owner only bypasses guest cap',async()=>{const r=await gd('/api/plan-live',{requestId:'cap-exhausted',theme:'Toys',approval:'I approve one paid planner attempt'});await worker.queue({messages:[{body:{version:1,kind:'planner',jobId:r.requestId},ack(){}}]},env);assert.equal((await gd('/api/planner?id='+r.requestId)).status,'blocked');assert.equal(textCalls,1);assert(await claimPaid(env,'owner-ok',100000000,'owner'));db.exec("UPDATE attempts SET status='complete',actual=reservation WHERE job_id='owner-ok';UPDATE budget SET historical_known=94900000000");assert.equal(await claimPaid(env,'owner-over-global',1,'owner'),false);});
await check('unknown attempt keeps shared reserve and blocks subsequent owners and guests',async()=>{db.exec("UPDATE budget SET historical_known=0;UPDATE attempts SET status='unknown',actual=NULL WHERE job_id='last-text'");assert.equal((await budgetState(env)).guest_remaining,0);assert.equal(await claimPaid(env,'unknown-owner',1,'owner'),false);assert.equal(await claimPaid(env,'unknown-guest',1,pb),false);});
console.log(JSON.stringify({passed:checks.length,providerCalls:0,mockedImageCalls:providerCalls,mockedTextCalls:textCalls,published:false}));
export {worker,env,token,bucket,db,runA,jobA};
if(!process.argv.includes('--keep-open'))db.close();
