import {createVisitorEntry} from '../cloudflare/visitor-entry.mjs';
import {budgetState,claimPaid} from '../cloudflare/budget.mjs';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFile } from 'node:fs/promises';
import { createWorker,processJob } from '../cloudflare/worker.mjs';
import { sha,imageRequest,usageCost,IMAGE_MODEL } from '../cloudflare/provider.mjs';
import { mockPNG,decodePNG,finalPNG } from '../cloudflare/png.mjs';
const db=new DatabaseSync(':memory:');db.exec(await readFile(new URL('../cloudflare/schema.sql',import.meta.url),'utf8'));
function statement(sql,args=[]){return {bind(...a){return statement(sql,a);},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};},sql,args};}
const DB={prepare:statement,async batch(items){db.exec('BEGIN');try{const results=[];for(const s of items)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};
class Bucket{constructor(){this.map=new Map();this.fail=null;}async put(k,v){if(this.fail?.(k))throw Error('Injected R2 write failure');this.map.set(k,typeof v==='string'?new TextEncoder().encode(v):new Uint8Array(v));}async get(k){const v=this.map.get(k);return v?{body:new Blob([v]).stream(),arrayBuffer:async()=>v.slice().buffer,text:async()=>new TextDecoder().decode(v),json:async()=>JSON.parse(new TextDecoder().decode(v))}:null;}async head(k){return this.map.has(k)?{}:null;}}
const bucket=new Bucket(),messages=[];
const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk=await crypto.subtle.exportKey('jwk',keys.publicKey);jwk.kid='test';
const b64=x=>Buffer.from(typeof x==='string'?x:JSON.stringify(x)).toString('base64url');
async function jwt(overrides={}){const now=Math.floor(Date.now()/1000),content=b64({alg:'RS256',kid:'test'})+'.'+b64({iss:'https://offline-test.cloudflareaccess.com',aud:['test-aud'],email:'owner'+'@'+'example.invalid',iat:now,exp:now+600,...overrides});return content+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',keys.privateKey,new TextEncoder().encode(content))).toString('base64url');}
const token=await jwt(),env={DB,ARTIFACTS:bucket,IMAGE_JOBS:{async send(body){messages.push(body);}},ASSETS:{async fetch(){return new Response('<html>bootstrap</html>',{headers:{'Content-Type':'text/html'}});}},ACCESS_TEAM_DOMAIN:'https://offline-test.cloudflareaccess.com',ACCESS_AUD:'test-aud',OWNER_EMAIL:'owner'+'@'+'example.invalid',LIVE_GENERATION_ENABLED:'false'};
let providerCalls=0,providerMode='ok';const raw=await mockPNG(1376,1536);
const originalWorker=createWorker({authFetch:async()=>Response.json({keys:[jwk]}),provider:async()=>{providerCalls++;if(providerMode==='timeout')throw Error('Injected ambiguous timeout');return {png:raw,usage:{input_tokens:3,input_tokens_details:{text_tokens:1,image_tokens:2},output_tokens:4,total_tokens:7},requestId:'synthetic-request'};}});
async function call(path,body,options={}){return originalWorker.fetch(new Request('https://studio.example.invalid'+path,{method:body?'POST':'GET',headers:{'Cf-Access-Jwt-Assertion':options.token??token,...(body?{'Content-Type':'application/json',Origin:options.origin||'https://studio.example.invalid'}:{})},...(body?{body:JSON.stringify(body)}:{})}),options.env||env);}
async function data(path,body){const r=await call(path,body);const d=await r.json();assert(r.ok,JSON.stringify(d));return d;}
const visitor=createVisitorEntry({provider:async()=>{throw Error('No provider call allowed');}});env.PUBLIC_ASSETS=env.ASSETS;env.OWNER_PASSCODE='synthetic-owner-code-for-offline-tests-only';
const checks=[];async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
async function request(path,body,cookie='',ip='192.0.2.1',origin='https://studio.example.invalid'){return visitor.fetch(new Request('https://studio.example.invalid'+path,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json',Origin:origin}),...(cookie?{Cookie:cookie}:{}),'CF-Connecting-IP':ip},...(body===undefined?{}:{body:JSON.stringify(body)})}),env);}
const cookieOf=r=>r.headers.get('Set-Cookie')?.split(';')[0];let a,b,ca,cb,ownerCookie,jobId,runId;
await check('public editor works without Access variables or guest login',async()=>{delete env.ACCESS_AUD;delete env.ACCESS_TEAM_DOMAIN;delete env.OWNER_EMAIL;assert.equal((await request('/')).status,200);assert.equal((await request('/owner.html')).status,200);assert.equal((await request('/api/studies')).status,401);});
await check('anonymous sessions are opaque secure cookies with independent principals',async()=>{let r=await request('/api/guest/session',{});ca=cookieOf(r);a=await r.json();assert.equal(r.status,201);assert(r.headers.get('Set-Cookie').includes('Secure; HttpOnly; SameSite=Strict'));r=await request('/api/guest/session',{},'', '192.0.2.2');cb=cookieOf(r);b=await r.json();assert.notEqual(a.principalId,b.principalId);assert(!JSON.stringify(a).includes(ca.split('=')[1]));assert.equal(db.prepare('SELECT COUNT(*) n FROM anonymous_sessions').get().n,2);});
await check('Origin/CSRF and forged owner flags cannot elevate visitors',async()=>{assert.equal((await request('/api/owner/login',{passcode:env.OWNER_PASSCODE},'','192.0.2.3','https://other.invalid')).status,403);assert.equal((await request('/api/guest/session',{},'','192.0.2.3','https://other.invalid')).status,403);assert.equal((await request('/api/dispatch',{role:'owner',email:'owner'},ca)).status,403);assert.equal((await request('/api/studies',undefined,'__Host-card_owner=forged')).status,401);});
await check('owner login performs secure session issuance without exposing the secret',async()=>{assert.equal((await request('/api/owner/login',{passcode:'incorrect'},'','192.0.2.4')).status,401);const r=await request('/api/owner/login',{passcode:env.OWNER_PASSCODE},'','192.0.2.4');assert.equal(r.status,200);ownerCookie=cookieOf(r);assert(r.headers.get('Set-Cookie').includes('Max-Age=3600'));assert(!JSON.stringify(await r.json()).includes(env.OWNER_PASSCODE));assert.equal((await request('/api/preflight',undefined,ownerCookie)).status,200);});
await check('owner brute force throttles persist in D1',async()=>{for(let i=0;i<5;i++)assert.equal((await request('/api/owner/login',{passcode:'wrong'},'','192.0.2.5')).status,401);assert.equal((await request('/api/owner/login',{passcode:env.OWNER_PASSCODE},'','192.0.2.5')).status,429);});
await check('visitor mock result and responses remain session-isolated',async()=>{const r=await request('/api/runs',{mode:'mock',role:'owner',objects:[{object_id:'synthetic',brief:'synthetic fixture'}]},ca);assert.equal(r.status,201);runId=(await r.json()).runId;const own=await(await request('/api/run?run='+runId,undefined,ca)).json();jobId=own.jobs[0].id;assert.equal((await request('/api/run?run='+runId,undefined,cb,'192.0.2.2')).status,403);assert.equal(db.prepare('SELECT principal_id FROM runs WHERE id=?').get(runId).principal_id,a.principalId);await originalWorker.queue({messages:[{body:{version:1,jobId},ack(){}}]},env);assert.equal((await request('/api/asset?job='+jobId,undefined,ca)).status,200);assert.equal((await request('/api/asset?job='+jobId,undefined,cb,'192.0.2.2')).status,403);});
await check('private historical routes and paid visitor calls closed even with live env enabled',async()=>{env.LIVE_GENERATION_ENABLED='true';env.LIVE_PLANNER_ENABLED='true';for(const path of ['/editor/','/studio/index.html','/api/budget','/api/export?run='+runId,'/api/asset?job='+jobId+'&kind=raw','/api/asset?job='+jobId+'&kind=manifest'])assert.equal((await request(path,undefined,ca,'192.0.2.6')).status,403);assert.equal((await request('/api/plan-live',{role:'owner'},ca,'192.0.2.6')).status,403);assert.equal((await request('/api/runs',{mode:'live',objects:[{object_id:'x',brief:'x'}]},ca,'192.0.2.6')).status,403);});
await check('one shared lifetime $5 pool survives distinct sessions and browser reset',async()=>{db.exec('UPDATE budget SET approved=1,ceiling=100000000000');assert(await claimPaid(env,'visitor-prior',5000000000,a.principalId));db.exec("UPDATE attempts SET status='complete',actual=reservation WHERE job_id='visitor-prior'");assert.equal(await claimPaid(env,'new-browser',1,b.principalId),false);const r=await(await request('/api/guest/budget',undefined,cb)).json();assert.equal(r.remaining_nanodollars,0);assert.equal(r.ceiling_nanodollars,5000000000);assert(!('historical_known' in r));assert(await claimPaid(env,'owner-exempt-guest-only',1000000000,'owner'));db.exec("UPDATE attempts SET status='complete',actual=reservation WHERE job_id='owner-exempt-guest-only';UPDATE budget SET historical_known=94000000000");assert.equal(await claimPaid(env,'owner-global-block',1,'owner'),false);});
await check('unknown historical reserve stays intact',async()=>{db.exec('UPDATE budget SET historical_known=0,historical_unknown=1100000000');assert.equal(await claimPaid(env,'unknown-owner',1,'owner'),false);assert.equal((await budgetState(env)).historical_unknown,1100000000);});
await check('logout revokes server session; copied cookie no longer grants owner',async()=>{const r=await request('/api/owner/logout',{},ownerCookie,'192.0.2.7');assert.equal(r.status,200);assert(r.headers.get('Set-Cookie').includes('Max-Age=0'));assert.equal((await request('/api/preflight',undefined,ownerCookie,'192.0.2.7')).status,401);});
console.log(JSON.stringify({passed:checks.length,paidCalls:0,secretsCreated:0,published:false}));db.close();
