import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs/promises';import {createWorker} from '../cloudflare/worker.mjs';import {sha} from '../cloudflare/provider.mjs';
const db=new DatabaseSync(':memory:');db.exec(await fs.readFile('cloudflare/schema.sql','utf8'));const sql=await fs.readFile('private/site-migration/prepared/import-existing-study.sql','utf8');db.exec(sql);db.exec(sql);
function stmt(sql,args=[]){return{bind(...a){return stmt(sql,a)},async first(){return db.prepare(sql).get(...args)||null},async all(){return{results:db.prepare(sql).all(...args)}},async run(){return{meta:{changes:Number(db.prepare(sql).run(...args).changes)}}},sql,args}}
const DB={prepare:stmt,async batch(a){db.exec('BEGIN');try{const r=[];for(const s of a)r.push(await s.run());db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}};
const env={DB,ARTIFACTS:{async get(k){try{const b=await fs.readFile('private/site-migration/prepared/'+k);return{body:b,text:async()=>b.toString(),json:async()=>JSON.parse(b),arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}}catch{return null}}},ASSETS:{fetch:async()=>new Response('studio')},LIVE_GENERATION_ENABLED:'false',LIVE_PLANNER_ENABLED:'false'};
const worker=createWorker({authenticate:async()=>({role:'owner',principalId:'owner'}),provider:async()=>{throw Error('NO PROVIDER')}});async function request(path,body){return worker.fetch(new Request('https://test.invalid'+path,{method:body?'POST':'GET',headers:{Origin:'https://test.invalid','Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})}),env)}
const p=await(await request('/api/preflight')).json();assert.equal(p.review_ready,true);assert.equal(p.mock_ready,false);assert.deepEqual(p.missing,['IMAGE_JOBS']);assert.equal(p.budget.approved,0);const studies=await(await request('/api/studies')).json();assert.equal(studies.runs.length,1);const run=studies.runs[0];const d=await(await request('/api/run?run='+run.id)).json();assert.equal(d.jobs.length,20);let variants=0;
for(const j of d.jobs){const alts=JSON.parse(j.alternatives);variants+=alts.length;assert.equal(alts.length,3);assert.equal(j.revision,1);const m=await(await request('/api/image-info?job='+j.id)).json();const asset=await request('/api/asset?job='+j.id);assert.equal(await sha(new Uint8Array(await asset.arrayBuffer())),m.final_sha256);assert.equal(alts[0].config.layers.object,j.id);}
assert.equal(variants,60);assert.equal((await request('/api/export?run='+run.id)).status,200);const job=d.jobs[0];const body={jobId:job.id,eventId:'local-test-event',revision:2,action:'skip',diagnostics:{test:true}};assert.equal((await request('/api/choices',body)).status,200);assert.equal((await request('/api/choices',body)).status,200);assert.equal((await request('/api/choices',{...body,eventId:'conflict'})).status,409);assert.equal((await request('/api/runs',{mode:'mock'})).status,503);
const guest=createWorker({authenticate:async()=>({role:'anonymous-guest',principalId:'other'})});assert.equal((await guest.fetch(new Request('https://test.invalid/api/run?run='+run.id),env)).status,403);
console.log('PASS imported study: 20 unchanged PNG hashes, 60 frozen variants, 20 prior responses, idempotent import, D1+R2 without Queue, choice revision/idempotency, export, owner-only study, generation blocked; budget unchanged, paid calls 0.');db.close();
