import assert from 'node:assert/strict';import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import http from 'node:http';import {spawn} from 'node:child_process';import worker from '../cloudflare/public-demo-worker.mjs';import {decodePNG} from '../cloudflare/png.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),assets=path.join(root,'cloudflare/public-demo'),checks=[];function check(name,ok){assert(ok,name);checks.push(name);console.log('PASS '+name);}
const env={ASSETS:{async fetch(req){const n=new URL(req.url).pathname;try{const data=await fs.readFile(path.join(assets,n==='/'?'index.html':n.slice(1)));return new Response(data,{headers:{'Content-Type':n.endsWith('.js')?'text/javascript':n.endsWith('.css')?'text/css':'text/html'}});}catch{return new Response('Missing',{status:404});}}},LIVE_GENERATION_ENABLED:'true',OPENAI_API_KEY:'synthetic-not-real'};
for(const p of ['/','/index.html','/demo.js','/demo.css'])check('anonymous public '+p,(await worker.fetch(new Request('https://demo.invalid'+p),env)).status===200);
for(const p of ['/api/preflight','/api/runs','/api/asset?job=private','/editor/','/private/results.png','/assets/private.png','/cloudflare/worker.mjs'])check('private/backend denied '+p,(await worker.fetch(new Request('https://demo.invalid'+p),env)).status===403);
check('POST denied without relying on provider flags',(await worker.fetch(new Request('https://demo.invalid/',{method:'POST',body:'{}'}),env)).status===403);await assert.rejects(()=>worker.queue());check('queue disabled',true);
const server=http.createServer(async(req,res)=>{const r=await worker.fetch(new Request('http://127.0.0.1:5196'+req.url,{method:req.method}),env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));});await new Promise(r=>server.listen(5196,'127.0.0.1',r));
const profile=path.join(root,'qa-output/edge-public-demo');await fs.mkdir(profile,{recursive:true});const edge=spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--disable-gpu','--remote-debugging-port=9386','--user-data-dir='+profile,'--no-first-run','about:blank'],{stdio:'ignore',windowsHide:true});let ws,send;
try{let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch('http://127.0.0.1:9386/json')).json();break;}catch{await new Promise(r=>setTimeout(r,150));}}ws=new WebSocket(tabs.find(x=>x.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();ws.onmessage=e=>{const d=JSON.parse(e.data);if(pending.has(d.id)){pending.get(d.id)(d);pending.delete(d.id);}};send=(method,params={})=>new Promise(r=>{pending.set(++id,r);ws.send(JSON.stringify({id,method,params}));});const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.result.exceptionDetails)throw Error(JSON.stringify(r.result.exceptionDetails));return r.result.result.value;};await send('Page.navigate',{url:'http://127.0.0.1:5196/'});for(let i=0;i<60;i++){if(await ev('!!window.demoEngine'))break;await new Promise(r=>setTimeout(r,150));}
const result=await ev(`(()=>{const e=demoEngine,base=e.getState(),out={};const hash=c=>{const a=c.getContext('2d').getImageData(0,0,860,960).data;let h=0,count=0,zero=0;for(let i=0;i<a.length;i++){h=(h*31+a[i])>>>0;if(i%4===3){count+=a[i]>0;zero+=a[i]===0;}}return {h,count,zero};};for(const type of ['rings','stripes','rays','dots']){e.setState({...base,type});out[type]=hash(e.pattern());for(const [param,value]of [['scale',150],['thickness',40],['opacity',35],['x',75],['y',75],['color','#ffffff'],...(type==='rings'?[]:[['rotation',35]])]){e.setState({...base,type,[param]:value});out[type+'-'+param]=hash(e.pattern()).h!==out[type].h;}}e.setState(base);let bands=0,on=false;const a=e.pattern().getContext('2d').getImageData(0,0,860,960).data;for(let x=431;x<859;x++){const v=a[(480*860+x)*4+3]>100;if(v&&!on)bands++;on=v;}out.ringBands=bands;const m=e.manifest();e.setState({...base,x:200});e.apply(JSON.parse(JSON.stringify(m)));out.roundtrip=JSON.stringify(e.manifest())===JSON.stringify(m);e.setState({...base,type:'stripes',x:40,object:false});const underneath=e.compose().getContext('2d').getImageData(0,0,860,960).data;e.setState({...base,type:'stripes',x:40,object:true});const card=e.compose().getContext('2d').getImageData(0,0,860,960).data,source=e.object().getContext('2d').getImageData(0,0,860,960).data;let mismatch=0;for(let i=0;i<card.length;i+=4)if(source[i+3]===255)for(let c=0;c<4;c++)mismatch+=card[i+c]!==source[i+c];const p=(420*860+470)*4;out.occlusion=mismatch===0;out.hole=card.slice(p,p+4).every((v,i)=>v===underneath[p+i]);out.patternPNG=e.pattern().toDataURL();out.cardPNG=e.compose().toDataURL();e.setState({...base,opacity:0});out.zeroOpacity=hash(e.pattern()).count===0;out.requests=performance.getEntriesByType('resource').map(x=>x.name);return out;})()`);
for(const t of ['rings','stripes','rays','dots'])check(t+' nonempty and transparent gaps',result[t].count>0&&result[t].zero>0);
for(const [k,v]of Object.entries(result))if(k.includes('-'))check('parameter '+k,k==='stripes-y'?!v:v);
check('exactly three light rings',result.ringBands===3);check('manifest roundtrip',result.roundtrip);check('opaque foreground unaffected',result.occlusion);check('transparent hole reveals underlying pattern',result.hole);check('zero opacity transparent',result.zeroOpacity);
for(const k of ['patternPNG','cardPNG']){const image=await decodePNG(new Uint8Array(Buffer.from(result[k].split(',')[1],'base64')));check(k+' 860x960 RGBA',image.width===860&&image.height===960&&image.channels===4);if(k==='patternPNG')check('export alpha preserved',image.rgba.some((v,i)=>i%4===3&&v===0));}
check('no API/network resources',result.requests.every(u=>/^http:\/\/127\.0\.0\.1:5196\/(demo.js|demo.css|favicon.ico)$/.test(u)));
await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});check('mobile no horizontal overflow',await ev('document.documentElement.scrollWidth<=390'));
await fs.writeFile(path.join(root,'qa-output/public-demo-report.json'),JSON.stringify({passed:checks.length,checks,providerCalls:0,privateUploads:0},null,2));console.log(JSON.stringify({passed:checks.length,providerCalls:0,privateUploads:0}));
}finally{if(send)await send('Browser.close');ws?.close();edge.kill();server.close();}
