import assert from 'node:assert/strict';import fs from 'node:fs/promises';import http from 'node:http';import {spawn} from 'node:child_process';import {createHash} from 'node:crypto';import {createVisitorEntry} from '../cloudflare/visitor-entry.mjs';
const dir='cloudflare/visitor-public',prefix='/archive/latest-lora-test',m=JSON.parse(await fs.readFile(dir+prefix+'/test.json','utf8'));
assert.equal(m.assets.length,8);assert.deepEqual(m.gpt.objects,['011','022']);assert.deepEqual(m.gpt.candidates,['candidate-1','candidate-1']);assert.equal(m.flux.settings_verified_from_request_log,false);assert(m.findings_ru.basket.includes('намеренно'));assert(!JSON.stringify(m).includes('WesternV2'));
const assets={async fetch(req){let p=new URL(req.url).pathname;if(p===prefix||p===prefix+'/')p=prefix+'/index.html';if(p==='/archive')p='/archive.html';try{const data=await fs.readFile(dir+p);return new Response(req.method==='HEAD'?null:data,{headers:{'Content-Type':p.endsWith('.png')?'image/png':p.endsWith('.css')?'text/css':p.endsWith('.js')?'text/javascript':p.endsWith('.json')?'application/json':'text/html'}})}catch{return new Response(null,{status:404})}}};
const app=createVisitorEntry(),env={PUBLIC_ASSETS:assets};
for(const a of m.assets){const r=await app.fetch(new Request('http://localhost'+prefix+'/'+a.file),env);assert.equal(r.status,200);const data=Buffer.from(await r.arrayBuffer());assert.equal(createHash('sha256').update(data).digest('hex'),a.sha256);}
for(const path of [prefix,prefix+'/',prefix+'/test.json',prefix+'/style.css'])assert.equal((await app.fetch(new Request('http://localhost'+path),env)).status,200);
const source=await fs.readFile(dir+prefix+'/index.html','utf8');assert.equal((source.match(/<figure>/g)||[]).length,8);assert(!/<script|prompt_text|positive_prompt|negative_prompt/.test(source));
const server=http.createServer(async(req,res)=>{const r=await app.fetch(new Request('http://127.0.0.1:5207'+req.url),env);res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()))});await new Promise(r=>server.listen(5207,'127.0.0.1',r));await fs.mkdir('qa-output',{recursive:true});
const edge=spawn('C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',['--headless=new','--disable-gpu','--remote-debugging-port=9397','--user-data-dir='+process.cwd()+'/qa-output/edge-lora','--no-first-run','about:blank'],{stdio:'ignore',windowsHide:true});let ws,send;
try{let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch('http://127.0.0.1:9397/json')).json();break}catch{await new Promise(r=>setTimeout(r,150))}}ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();ws.onmessage=e=>{const d=JSON.parse(e.data);if(pending.has(d.id)){pending.get(d.id)(d);pending.delete(d.id)}};send=(method,params={})=>new Promise(r=>{pending.set(++id,r);ws.send(JSON.stringify({id,method,params}))});const ev=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.result.exceptionDetails)throw Error(JSON.stringify(r.result.exceptionDetails));return r.result.result.value};
 await send('Emulation.setDeviceMetricsOverride',{width:1400,height:1100,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:'http://127.0.0.1:5207'+prefix+'/'});
 for(let i=0;i<80;i++){if(await ev('document.images.length===8 && [...document.images].every(i=>i.complete&&i.naturalWidth>0)'))break;await new Promise(r=>setTimeout(r,100))}
 assert(await ev('document.images.length===8 && [...document.images].every(i=>i.complete&&i.naturalWidth>0)'));assert.equal(await ev('getComputedStyle(document.querySelector(".comparison")).gridTemplateColumns.split(" ").length'),4);assert.equal(await ev('document.querySelectorAll(".object-row").length'),2);
 await fs.writeFile('qa-output/latest-lora-desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).result.data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert(await ev('document.documentElement.scrollWidth<=390'));assert.equal(await ev('getComputedStyle(document.querySelector(".comparison")).gridTemplateColumns.split(" ").length'),2);await ev('document.querySelector(".object-row").scrollIntoView()');await fs.writeFile('qa-output/latest-lora-mobile.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).result.data,'base64'));
 console.log(JSON.stringify({passed:true,images:8,hashVerified:true,anonymous:true,desktopColumns:4,mobileColumns:2,mobileWidth:390,fullPromptsPublished:false,paidCalls:0}));
}finally{if(send)await send('Browser.close');ws?.close();edge.kill();server.close()}
