import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFile } from 'node:fs/promises';
import { createWorker,processJob } from '../cloudflare/worker.mjs';
import { sha,imageRequest,usageCost,IMAGE_MODEL } from '../cloudflare/provider.mjs';
import { mockPNG,decodePNG,finalPNG } from '../cloudflare/png.mjs';
const db=new DatabaseSync(':memory:');db.exec(await readFile(new URL('../cloudflare/schema.sql',import.meta.url),'utf8'));
function statement(sql,args=[]){return {bind(...a){return statement(sql,a);},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:Number(r.changes)}};},sql,args};}
const DB={prepare:statement,async batch(items){db.exec('BEGIN');try{const results=[];for(const s of items)results.push(await s.run());db.exec('COMMIT');return results;}catch(e){db.exec('ROLLBACK');throw e;}}};
class Bucket{constructor(){this.map=new Map();this.fail=null;}async put(k,v){if(this.fail?.(k))throw Error('Injected R2 write failure');this.map.set(k,typeof v==='string'?new TextEncoder().encode(v):new Uint8Array(v));}async get(k){const v=this.map.get(k);return v?{body:new Blob([v]).stream(),arrayBuffer:async()=>v.slice().buffer,text:async()=>new TextDecoder().decode(v),json:async()=>JSON.parse(new TextDecoder().decode(v))}:null;}async head(k){return this.map.has(k)?{}:null;}}
const bucket=new Bucket(),messages=[];
const keys=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk=await crypto.subtle.exportKey('jwk',keys.publicKey);jwk.kid='test';
const b64=x=>Buffer.from(typeof x==='string'?x:JSON.stringify(x)).toString('base64url');
async function jwt(overrides={}){const now=Math.floor(Date.now()/1000),content=b64({alg:'RS256',kid:'test'})+'.'+b64({iss:'https://offline-test.cloudflareaccess.com',aud:['test-aud'],email:'owner'+'@'+'example.invalid',iat:now,exp:now+600,...overrides});return content+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',keys.privateKey,new TextEncoder().encode(content))).toString('base64url');}
const token=await jwt(),env={DB,ARTIFACTS:bucket,IMAGE_JOBS:{async send(body){messages.push(body);}},ASSETS:{async fetch(){return new Response('<html>bootstrap</html>',{headers:{'Content-Type':'text/html'}});}},ACCESS_TEAM_DOMAIN:'https://offline-test.cloudflareaccess.com',ACCESS_AUD:'test-aud',OWNER_EMAIL:'owner'+'@'+'example.invalid',LIVE_GENERATION_ENABLED:'false'};
let providerCalls=0,providerMode='ok';const raw=await mockPNG(1376,1536);
const worker=createWorker({authFetch:async()=>Response.json({keys:[jwk]}),provider:async()=>{providerCalls++;if(providerMode==='timeout')throw Error('Injected ambiguous timeout');return {png:raw,usage:{input_tokens:3,input_tokens_details:{text_tokens:1,image_tokens:2},output_tokens:4,total_tokens:7},requestId:'synthetic-request'};}});
async function call(path,body,options={}){return worker.fetch(new Request('https://studio.example.invalid'+path,{method:body?'POST':'GET',headers:{'Cf-Access-Jwt-Assertion':options.token??token,...(body?{'Content-Type':'application/json',Origin:options.origin||'https://studio.example.invalid'}:{})},...(body?{body:JSON.stringify(body)}:{})}),options.env||env);}
async function data(path,body){const r=await call(path,body);const d=await r.json();assert(r.ok,JSON.stringify(d));return d;}
const checks=[];async function check(name,fn){await fn();checks.push(name);console.log('PASS '+name);}
await check('all static/API routes fail closed, signature/owner/audience/expiry/CSRF',async()=>{for(const path of ['/','/app.js','/api/preflight','/api/asset?job=x'])assert.equal((await call(path,null,{token:'bad'})).status,401);assert.equal((await call('/',null,{env:{...env,ACCESS_AUD:''}})).status,503);for(const c of [{aud:['wrong']},{exp:0},{iss:'https://bad.invalid'}])assert.equal((await call('/',null,{token:await jwt(c)})).status,401);assert.equal((await call('/',null,{token:await jwt({email:'other'+'@'+'example.invalid'})})).status,403);assert.equal((await call('/api/runs',{}, {origin:'https://other.invalid'})).status,403);const r=await call('/');assert.equal(r.status,200);assert(r.headers.get('Content-Security-Policy').includes("frame-ancestors 'none'"));});
await check('authorized preflight shows missing bindings; live default blocked',async()=>{const r=await call('/api/preflight',null,{env:{...env,DB:null,ARTIFACTS:null}}),d=await r.json();assert(!d.mock_ready);assert(d.missing.includes('DB'));assert.equal((await call('/api/runs',{mode:'live',objects:[{object_id:'x',brief:'test'}]})).status,403);assert.equal(providerCalls,0);});
let mockRun,job;
await check('versioned planner mock and 20-job D1/R2/queue flow',async()=>{const p=await data('/api/plan-mock',{theme:'Toys'});assert.equal(p.objects.length,20);assert.equal(p.llm_inference,false);mockRun=await data('/api/runs',{objects:p.objects,name:'Offline 20'});assert.equal(messages.length,20);for(const body of messages.splice(0)){let ack=0;await worker.queue({messages:[{body,ack(){ack++;}}]},env);assert.equal(ack,1);}const run=await data('/api/run?run='+mockRun.runId);assert.equal(run.jobs.filter(j=>j.status==='complete').length,20);job=run.jobs[0];assert.equal(providerCalls,0);});
await check('PNG native/final dimensions, alpha, holes, content hashes and manifest',async()=>{for(const [kind,w,h] of [['raw',1376,1536],['final',860,960]]){const r=await call(`/api/asset?job=${job.id}&kind=${kind}`),png=await decodePNG(new Uint8Array(await r.arrayBuffer()));assert.equal(png.width,w);assert.equal(png.height,h);assert.equal(png.rgba[3],0);assert.equal(png.rgba[(Math.round(h*.43)*w+Math.round(w*.58))*4+3],0);assert.equal(png.rgba[(Math.round(h*.49)*w+Math.round(w*.4))*4+3],255);}const manifest=await data(`/api/asset?job=${job.id}&kind=manifest`);assert.equal(manifest.cost_nanodollars,0);assert.equal(manifest.final_sha256,await sha(bucket.map.get(manifest.final_key)));});
await check('immutable candidates, choice CAS/idempotency/none/undo, persisted export',async()=>{const alternatives=[0,1,2].map(i=>({id:'v'+i,config:{background:'#abcdef'}}));await data('/api/candidates',{jobId:job.id,alternatives});assert.equal((await call('/api/candidates',{jobId:job.id,alternatives:alternatives.map(a=>({...a,config:{x:1}}))})).status,409);const b={jobId:job.id,eventId:'event1',revision:1,action:'select',selected:'v1'};await data('/api/choices',b);assert((await data('/api/choices',b)).idempotent);assert.equal((await call('/api/choices',{...b,eventId:'stale'})).status,409);await data('/api/choices',{jobId:job.id,eventId:'event2',revision:2,action:'none'});await data('/api/choices',{jobId:job.id,eventId:'event3',revision:3,action:'undo'});const exported=await data('/api/export?run='+mockRun.runId);assert.equal(exported.events.length,3);assert.equal(exported.candidates.length,1);assert.equal(JSON.parse(exported.events[2].payload).action,'undo');});
await check('outbox survives enqueue failure and duplicate delivery',async()=>{const send=env.IMAGE_JOBS.send;env.IMAGE_JOBS.send=async()=>{throw Error('offline');};const r=await data('/api/runs',{objects:[{object_id:'outbox',brief:'test'}]});assert(r.queue_pending);env.IMAGE_JOBS.send=send;assert.equal((await data('/api/dispatch',{})).sent,1);const msg=messages.pop();await worker.queue({messages:[{body:msg,ack(){}}]},env);await worker.queue({messages:[{body:msg,ack(){}}]},env);assert.equal(db.prepare('SELECT COUNT(*) n FROM attempts WHERE job_id=?').get(msg.jobId).n,1);});
// Fake reference fixtures and fake provider only. No network, credentials or real reference images.
const sheet=await mockPNG(896,1040),sheetSha=await sha(sheet),ad='Synthetic offline Art Direction';const reference={version:'reference-pack/v1',model:IMAGE_MODEL,reference_count:50,art_direction:ad,art_direction_sha256:await sha(ad),sheets:Array.from({length:13},(_,i)=>({key:'references/sheet'+i+'.png',count:i===12?2:4,sha256:sheetSha}))};for(const s of reference.sheets)await bucket.put(s.key,sheet);const manifestText=JSON.stringify(reference);await bucket.put('references/manifest.json',manifestText);Object.assign(env,{LIVE_GENERATION_ENABLED:'true',OPENAI_API_KEY:'synthetic-not-a-credential',REFERENCE_MANIFEST_KEY:'references/manifest.json',APPROVED_REFERENCE_MANIFEST_SHA256:await sha(manifestText),APPROVED_ART_DIRECTION_SHA256:await sha(ad)});db.exec('UPDATE budget SET approved=1,ceiling=100000000000');
async function liveRun(objectId){return data('/api/runs',{mode:'live',approval:'I approve one paid attempt per object',objects:[{object_id:objectId,brief:'synthetic'}]});}
await check('atomic duplicate live claim invokes mocked provider once',async()=>{const r=await liveRun('atomic'),j=(await data('/api/run?run='+r.runId)).jobs[0];const batch=()=>worker.queue({messages:[{body:{version:1,jobId:j.id},ack(){}}]},env);await Promise.all([batch(),batch()]);assert.equal(providerCalls,1);assert.equal(db.prepare('SELECT status FROM attempts WHERE job_id=?').get(j.id).status,'complete');});
await check('failure after response: durable receipt recovers with zero provider retries',async()=>{const r=await liveRun('storage'),j=(await data('/api/run?run='+r.runId)).jobs[0];bucket.fail=k=>k.endsWith('/final.png');await worker.queue({messages:[{body:{version:1,jobId:j.id},ack(){}}]},env);assert.equal(providerCalls,2);assert.equal(db.prepare('SELECT status FROM attempts WHERE job_id=?').get(j.id).status,'unknown');bucket.fail=null;await data('/api/recover',{jobId:j.id});assert.equal(providerCalls,2);assert.equal(db.prepare('SELECT status FROM attempts WHERE job_id=?').get(j.id).status,'complete');});
await check('ambiguous timeout retains reservation; replay and subsequent live work blocked',async()=>{providerMode='timeout';const r=await liveRun('timeout'),j=(await data('/api/run?run='+r.runId)).jobs[0];for(let i=0;i<2;i++)await worker.queue({messages:[{body:{version:1,jobId:j.id},ack(){}}]},env);assert.equal(providerCalls,3);const attempt=db.prepare('SELECT * FROM attempts WHERE job_id=?').get(j.id);assert.equal(attempt.status,'unknown');assert.equal(attempt.reservation,1000000000);assert.equal((await call('/api/recover',{jobId:j.id})).status,409);const blocked=await call('/api/runs',{mode:'live',approval:'I approve one paid attempt per object',objects:[{object_id:'blocked',brief:'test'}]});assert.equal(blocked.status,409);assert.equal(providerCalls,3);});
await check('adapter exact multipart contract and zero retries on 429',async()=>{let calls=0;await assert.rejects(()=>imageRequest(env,'synthetic',Array(13).fill(sheet),async(url,init)=>{calls++;assert.equal(url,'https://api.openai.com/v1/images/edits');assert.equal(init.body.get('model'),IMAGE_MODEL);assert.equal(init.body.getAll('image[]').length,13);assert.equal(init.body.get('size'),'1376x1536');assert.equal(init.body.get('background'),'transparent');assert.equal(init.redirect,'error');return new Response('',{status:429});}));assert.equal(calls,1);assert.equal(usageCost({}),null);assert.equal(usageCost({input_tokens:3,input_tokens_details:{text_tokens:1,image_tokens:2},output_tokens:4,total_tokens:7}),141000);});
await check('PNG corruption and unsupported dimensions reject',async()=>{const bad=raw.slice();bad[40]^=1;await assert.rejects(()=>decodePNG(bad));await assert.rejects(()=>finalPNG(sheet));});
await check('stable run id rejects changed payload and double clicks',async()=>{const body={mode:'mock',requestId:'stable-double-click',objects:[{object_id:'one',name:'One card',category:'C3',brief:'same'}]};const a=await data('/api/runs',body),b=await data('/api/runs',body);assert.equal(a.runId,b.runId);const metadata=(await data('/api/run?run='+a.runId)).jobs[0];assert.equal(metadata.name,'One card');assert.equal(metadata.category,'C3');assert.equal(metadata.asset_stage,'object_with_surface');assert.equal(metadata.prompt,undefined);assert.equal(db.prepare('SELECT COUNT(*) n FROM jobs WHERE run_id=?').get(a.runId).n,1);assert.equal((await call('/api/runs',{...body,objects:[{object_id:'one',brief:'changed'}]})).status,409);});
console.log(JSON.stringify({passed:checks.length,checks,externalRequests:0,paidRequests:0,mockedLiveRequests:providerCalls}));
db.close();
